### ISSUE TITLE
Remove/Customize Vendor Executable Icon in Notification

### ISSUE THREAD

**Issue by MadLittleMods** [mikaelbr/node-notifier#100]
Some platforms show the executable icon which is seems to be none and doesn't look the best. Add a way to customize this icon.

Windows 8.1 (default Windows no-icon-provided application icon)
![](http://i.imgur.com/HObLa2w.png)

Mac OSX (terminal looking icon)
![](https://i.imgur.com/BHLXShe.png)

**Comment by kurisubrooks** [comment]
Due to the way OS X Notifications work, the terminal icon can only be removed by recompiling terminal-notifier.app with your app's .icns, then leaving the `image` option blank (to use the default). Check #71

**Comment by MadLittleMods** [comment]
For reference images of the notifications on different platforms (I only provided ones that include the vendor app icon here): https://github.com/gitterHQ/desktop/pull/100#issue-131554885

Here are maybe some solutions for each platform:

OSX:
 - http://codefromabove.com/2015/03/programmatically-adding-an-icon-to-a-folder-or-file/

Windows:
 - (untested) Create a shortcut with a custom icon

**Comment by kurisubrooks** [comment]
The reason I recommended recompiling terminal-notifier with the custom .icns, is because of how OS X caches images. You can of course change the image by dropping it into the Get Info pane, but this is glitchy and doesn't guarantee being held when distributed from system to system.

If you find a fix for the Windows 8 notification, please let me know!

**Comment by mikaelbr** [comment]
I think this unfortunately is a wont-fix and I'm closing it. If we find another better way to do this we should document it in the readme or similar.

**Comment by laxmikanta415** [comment]
This solved my problem and you only need to have your icns file ready: 

run this command in terminal  after downloading :customise-terminal-notifier 

** path/customise-terminal-notifier-master/customise-terminal-notifier -i path/Terminal.icns  -b com.bundle.identifier
