### ISSUE TITLE
Sanitize `response` on callback

### ISSUE THREAD

**Issue by MadLittleMods** [mikaelbr/node-notifier#101]
Sanitize `response` before passing it onto the consumer. Something simple like `response.trim().toLowerCase();` would be great (also need to take care of disparity, see below).

Currently(tested on Windows) when the toaster binary responds, it will have a newline on the end which makes it easy to fall in a trap when trying to use it in a if statement. `'Activated\n'`

A disparity between OSX and Windows is also `Activate` vs `Activated`

```js
notifier.notify({
  title: opts.title,
  message: opts.message,
  // wait with callback until user action is taken on notification
  wait: true
}, function(err, response) {
  // response = 'Activated\n' || `Activate`
});
```

I am pretty sure this is caused by `Console.WriteLine("Activated");` in toaster.exe source: https://github.com/mikaelbr/toaster/blob/8d8eb7fbe77d2c8730756f1c3d63268b5b9d838e/toast/Program.cs#L256

**Comment by mikaelbr** [comment]
Sounds good to me! I can give you collaborator access if you wish to fix this yourself as well?

**Comment by MadLittleMods** [comment]
@mikaelbr :+1:

I would also be interested in adding the fix upstream to toaster which I assume is a simple `Console.Write` instead of `Console.WriteLine`. Is the `silent` branch the most up to date you build the binary from?

**Comment by mikaelbr** [comment]
I've added you as a collaborator now! :cake: :tada: 

Yeah, it's the `silent` branch, as I have a PR here: https://github.com/nels-o/toaster/pull/4 (which I guess won't be merged anytime soon...)

**Comment by mikaelbr** [comment]
I think though, as `toaster` is also a CLI it makes more sense to have `Console.WriteLine` instead of `Console.Write` to have a correct output to the command line. It's better for `node-notifier` to clean up and trim.

**Comment by MadLittleMods** [comment]
@mikaelbr PR for `node-notifier` https://github.com/mikaelbr/node-notifier/pull/103 and upstream `toaster`: https://github.com/mikaelbr/toaster/pull/2

**Comment by mikaelbr** [comment]
This should probably be closed now
