### ISSUE TITLE
Cannot work using windows growl remotely

### ISSUE THREAD

**Issue by el-davo** [mikaelbr/node-notifier#104]
Hi There

Ive been trying to get the growl notifier to work with a remote windows growl downloaded here - http://www.growlforwindows.com/gfw/ It works wonderfully when i am sending the notification on the same machine as the program above is installed on. However I cannot get this to work on a remote host.

I drilled into to the code a bit and found an error message after doing some logging this is what it produces
```
{ 
  state: 'ERROR',
  'Error-Code': '400',
  'Error-Description': 'Missing key hash',
  'Origin-Machine-Name': 'AHERND2-WIN7-02',
  'Origin-Software-Name': 'Growl/Win',
  'Origin-Software-Version': '2.0.9.1',
  'Origin-Platform-Name': 'Microsoft Windows NT 6.1.7601 Service Pack 1',
  'Origin-Platform-Version': '6.1.7601.65536',
  'X-Message-Daemon': 'Growl/Win',
  'X-Timestamp': '01/03/2016 16:58:54' 
}
```

After doing some googling It seems that you also need to send a password along with the notification

```
var Growl = require('node-notifier/notifiers/growl');

new Growl({
            host: '10.73.66.153',
            port: 23053
}).notify({
            title: 'test',
            message: 'test',
            icon: __dirname + '/../../assets/angular-fail.png',
            wait: false,
            sticky: false,
            label: void 0,
            priority: void 0
}, function (error, response) {
    if (error) {
        console.log(error);
    }
   done();
});
```

Is sending a password supported? And if so how do I send it. And if not Have you any ideas how else to make it work?

Many thanks

**Comment by mikaelbr** [comment]
Have you seen this: https://github.com/jcgay/send-notification/wiki/Growl-(Windows)?

If password is needed, this is a change that will have to be merged all the way to [growly](https://github.com/theabraham/growly). As of now, there is no way to pass on password via the GNTP.

**Comment by el-davo** [comment]
Thanks for the response. I figured out a workaround for now. I use snarl as the central server and you can post notification to snarl without needing a password. You can also make windows growl subscribe to snarl without problem, and it just seems to work, So if anyone is looking for a solution this is what i did

**Comment by mikaelbr** [comment]
Ah. Sorry. I read the wrong issue when fixing another issue so accidentally closed this. Reopened now

**Comment by mikaelbr** [comment]
But it seems you found a workaround, so closing anyways! Thanks for letting us know how you fixed it.

**Comment by el-davo** [comment]
No problem
