### ISSUE TITLE
String input fails on linux

### ISSUE THREAD

**Issue by spadgos** [mikaelbr/node-notifier#105]
The example code in the readme does not work on Linux:

```js
notifier.notify('Title', 'Message');
```

It appears as though the bug is in [`notifiers/notifysend.js`](https://github.com/mikaelbr/node-notifier/blob/master/notifiers/notifysend.js#L28-L66)

When passing two strings, the `callback` is set to be the value of the second string, and then is never updated again to be a function.

**Comment by spadgos** [comment]
I was going to fix this with a PR, but maybe the bug is the documentation? This format of calling `.notify(string, string)` is not in any of the tests, or mentioned anywhere else.

**Comment by mikaelbr** [comment]
Hi and thanks for your issue! This is unfortunately a bug in the documentation. I've updated the docs now. Sorry about that and thanks for letting me know

**Comment by spadgos** [comment]
Cool, no worries.
