### ISSUE TITLE
How to use cli to post to remote server

### ISSUE THREAD

**Issue by el-davo** [mikaelbr/node-notifier#106]
Hi Sorry for opening another issue. This is more of a general query around the cli use. Is there a way to send a message to a remote server using the cli. for example maybe something like

notify -t title -m message --host=10.74.55.66 --port=23053

**Comment by el-davo** [comment]
Hello. I still cant get this to work. It seems to always send to localhost. I have installed the latest version and used the cmd below

    notify --host 10.73.66.153 --port 23053 -m "test"

**Comment by mikaelbr** [comment]
Hi! It hit's me that I've might misunderstood the requirement here. You are trying to pass host and port to a Growl implementation, yes?

**Comment by el-davo** [comment]
Yes the way i have this setup is i have growl running on a remote server. I then want to send a notification to that server which in turns sends a notification out to all subscribers of that server. But trying the command above i do see a notification bubble on my local machine but not on the remote server

**Comment by mikaelbr** [comment]
I don't have Growl on this machine so I can't test from end-to-end, but when I try running:

```
notify --host 127.0.0.1 --port 3000 -m Hello
```

And right before the notification is sent I print out the host and port, I get `127.0.0.1:3000`, which is what I expect.

Do you get any error? You are sure you are running `node-notifier@4.6.0` (verify by using `npm ls node-notifier`).

**Comment by el-davo** [comment]
Yep i have the latest version - 4.6.0. Didn't see any errors either.

I can do some debugging and get back to you. 

Also its just the cli im talking about the node implementation works perfecto and have been using it for a long time now!!

**Comment by mikaelbr** [comment]
Would be great if you could do some digging 👍 You could try printing out options in the `Growl` constructor function, inside `checkGrowl` in `checkGrowl.js` and inside notify in the Growly package
