### ISSUE TITLE
Not working on osx

### ISSUE THREAD

**Issue by burakcan** [mikaelbr/node-notifier#107]
Hi, i am trying to integrate this into an electron app. When i call `.notify` method; it does absolute nothing with no errors.
I also tried the cli with global installation but it didn't work either.

<img width="272" alt="screen shot 2016-03-04 at 09 42 00" src="https://cloud.githubusercontent.com/assets/3121257/13520948/5d1c3f22-e1ed-11e5-8d4d-b7572fd2dac3.png">

my osx version: 10.11.3 (15D21)
node version: v5.7.0

**Comment by burakcan** [comment]
SOLVED: Sorry; it turns out that i didnt read document properly. My problem is related to tmux which is explicitly described :)

**Comment by mikaelbr** [comment]
Glad it worked out for you!
