### ISSUE TITLE
Set Active Monitor

### ISSUE THREAD

**Issue by Givemeyourgits** [mikaelbr/node-notifier#108]
Unless I missed it, there doesn't seem to be a way to set what monitor the notifications come up on.  I would like to have it display on a secondary monitor rather than the main display.

Is there a way to do this?

**Comment by kurisubrooks** [comment]
node-notifier wraps modules that interact with each operating system's default notifiers. unfortunately i'm unaware of any features that would allow us to change this, so it inherits the system's default settings. Sorry :disappointed:

**Comment by kurisubrooks** [comment]
I'll leave this open to get @mikaelbr's feedback to see what he has to say on the matter.

**Comment by mikaelbr** [comment]
I'm sorry. As far as I know this isn't possible programatically. And for Notification Center (Mac) this isn't possible at all, I think.
