### ISSUE TITLE
Move CLI tool to separate project/package

### ISSUE THREAD

**Issue by Turbo87** [mikaelbr/node-notifier#116]
The `node-notifier` project on NPM seems to depend on the `minimist` and `cli-usage` packages, which are only used by the `notify` CLI tool. Most projects that depend on `node-notifier` however don't need these dependencies and the sub-dependencies of them. A solution to that would be to extract the CLI tool (or the library code) into a separate project and remove the CLI-related dependencies from this one.

**Comment by Turbo87** [comment]
@mikaelbr any opinions on this?

**Comment by mikaelbr** [comment]
Hi @Turbo87! Are your concerns primarily the size of the module or the principle of it? While having a separate CLI-module could be a possibility, it isn't too unusual pattern to have cli features baked in as a part of the original package (e.g. https://www.npmjs.com/package/watch or https://www.npmjs.com/package/onchange)

**Comment by Turbo87** [comment]
@mikaelbr my concern is the number of dependencies that npm has to download if this project is just used as a library. it's not a huge issue on small projects but unfortunately these things add up.

**Comment by mikaelbr** [comment]
Hi. Sorry for the late response on this. I've been thinking about it, and I think the convenience and the adaptation of using the CLI tool outweighs the additional overhead of having a few extra packages. Maybe at some point I'll look into not using dependencies for this (as it has a fairly trivial binary API), but for now I'm thinking the default dedupe in NPM 3 makes this not as critical.

I'm closing this for now, but feel free re-open.

**Comment by wtgtybhertgeghgtwtg** [comment]
I took a look at the top five dependents of `node-notifier` ([`jest-cli`](https://www.npmjs.com/package/jest-cli), [`testem`](https://www.npmjs.com/package/testem), [`gulp-notify`](https://www.npmjs.com/package/gulp-notify), [`webpack-notifier`](https://www.npmjs.com/package/webpack-notifier), and [`gulp-phpunit`](https://www.npmjs.com/package/gulp-phpunit)) and none of them use the CLI.  Since they seem to constitute almost all of the downloads of `node-notifier`, maybe spinning off the CLI could be reconsidered?

**Comment by mikaelbr** [comment]
We're looking at a breaking change now when we add reply and switch out toaster, so I'll look into this.

**Comment by wtgtybhertgeghgtwtg** [comment]
Thank you for considering.

**Comment by mikaelbr** [comment]
As of v5 this should happen: https://github.com/mikaelbr/node-notifier-cli

**Comment by wtgtybhertgeghgtwtg** [comment]
I am looking forward to it.  Thank you.
