### ISSUE TITLE
Does not work on El Capitan

### ISSUE THREAD

**Issue by IonicaBizau** [mikaelbr/node-notifier#119]
I looks like this module doesn't work on my Macbook Air 13", running El Capitan. Any ideas?

**Comment by kurisubrooks** [comment]
Can I please have your exact code usage? I'm running it just fine on El Capitan, as well as all of my co workers.

**Comment by IonicaBizau** [comment]
I executed `node example/message.js`.

It works fine on my Linux machines, but on El Capitan the notification does not appear. The terminal logs do appear (“Waited” and “Exit” or so).

**Comment by kurisubrooks** [comment]
That example hasn't been updated in a while. I'll give it a test and let you know.

**Comment by kurisubrooks** [comment]
![image](https://cloud.githubusercontent.com/assets/6291467/15282250/52a7f8b6-1b85-11e6-862c-eef96d687dbb.png)

The example is working for me.
Do you have any error messages in the Terminal? Did you remember to `npm install` in the parent directory?

**Comment by IonicaBizau** [comment]
Nope, no errors… I did `npm install` the things. Actually I cloned the repo itself and I `npm install`ed.

**Comment by kurisubrooks** [comment]
That's what I just did, but i'm unsure as to why the example isn't working for you.
If you `sudo npm i node-notifier -g` then run `notify -t "Hello" -m "World"`, are you able to get a notification?

**Comment by IonicaBizau** [comment]
@kurisubrooks `notify -t "Hello" -m "World"` doesn't output any errors, but the process remains opened. No notification shown... 😭  Should I install any binaries or so?

**Comment by IonicaBizau** [comment]
@kurisubrooks `.../vendor/terminal-notifier.app/Contents/MacOS/terminal-notifier -message hello -wait YES` doesn't work, so the problem is somewhere in there... 💥

**Comment by kurisubrooks** [comment]
The binaries are installed with the module.
Just out of curiosity, what are your App Security settings set to?
`System Preferences > Security & Privacy > General > Allow apps from %%%` (Near the bottom)

**Comment by IonicaBizau** [comment]
*from Anywhere*—hmmm. Otherwise I would expect an error when executing that binary, or?

![screen shot 2016-05-16 at 09 57 22](https://cloud.githubusercontent.com/assets/2864371/15282547/aaa7d10a-1b4c-11e6-8347-bc1c3ba7c793.png)

**Comment by kurisubrooks** [comment]
I was unsure if using the app via CLI would trigger a security error, but if you're set to Anywhere, I have absolutely no idea what's causing this. I think the problem might be with `terminal-notifier` therefore Upstream, but that project is inactive so you wouldn't be able to get much support from there.

I'll assign @mikaelbr to this Issue and he can give his input on this, maybe try to figure out what's wrong. Sorry I couldn't help.

**Comment by IonicaBizau** [comment]
Thanks for fast feedback I appreciate it. If you have any questions, let me know. 🔔

**Comment by IonicaBizau** [comment]
Hmm, it looks like I cannot reproduce the issue anymore. What I did in the meantime I installed the updates and restarted the machine. Not sure why it was broken and why now it works. 😁

Should we keep this opened?

**Comment by mikaelbr** [comment]
I couldn't reproduce it myself, but haven't had the time to dig too deep into the issue. Glad it worked out for you. I think we can close the issue and if it occurs again with someone we can reopen it. Thanks for your help and letting us know!

**Comment by IonicaBizau** [comment]
Thanks 👍

**Comment by neouser99** [comment]
This may not be resolved, I'm seeing similar symptoms. El Capitan, node 6.2.0, node-notifier@master, it just hangs.

    npm i -g node-notifier
    notify -m 'something' -t 'Something'

**Comment by kurisubrooks** [comment]
@neouser99 What terminal are you using?

**Comment by neouser99** [comment]
iterm2 3.0.5 w/ tmux

**Comment by kurisubrooks** [comment]
This is a known bug.
Please refer to https://github.com/mikaelbr/node-notifier#use-inside-tmux-session

**Comment by neouser99** [comment]
That does the trick. I even noticed that section, and for some reason completed glossed over it. Thanks for the help @kurisubrooks, sorry for the tangent.
