### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by gucong3000** [mikaelbr/node-notifier#121]
Like: 4.5.1

**Comment by mikaelbr** [comment]
Hi! See https://github.com/mikaelbr/node-notifier/pull/103#issuecomment-221008109 for info on release.

**Comment by kurisubrooks** [comment]
We're preparing some more code changes before pushing a new release, but it's something we'll be doing soon. If you want, you can always download the latest version from our repos through npm with `npm install mikaelbr/node-notifier`

**Comment by mikaelbr** [comment]
Thanks for letting us know and pushing us to prioritize this 👍 Version `4.6.0` is out now with some fixes and additions: https://github.com/mikaelbr/node-notifier/blob/master/CHANGELOG.md#v460

**Comment by gucong3000** [comment]
:+1:
