### ISSUE TITLE
Notifier Icon not showing on windows after building Electron app

### ISSUE THREAD

**Issue by epezhman** [mikaelbr/node-notifier#124]
Hi, I'm making an `electron `app, the notifier works fine on Windows 10 when running in development but after packing and installing on my computer (using `electron-builder 5.10.2`) the notification still works but the icon is not showing. I unpacked the notifier from my `asar `and also the icon, so I have it like `app.asar.unpacked\node_modules\node-notifier\vendor\**` and `app.asar.unpacked\assets\**` (assets contain my icons), any idea why not working? thanks

my notify module:

```
'use strict'

module.exports = notify

const notifier = require('node-notifier')
const config = require('../config')

function notify(msg) {
    notifier.notify({
        title: config.APP_NAME,
        message: msg,
        icon: config.APP_ICON
    })
}
```

the config.APP_ICON:

`APP_ICON: path.join(__dirname, 'assets/img/icon.png')`

in development: 
![dev](https://cloud.githubusercontent.com/assets/3763134/16516311/b1b2296a-3f77-11e6-9782-df9b2a2d295a.PNG)

in production:
![pro](https://cloud.githubusercontent.com/assets/3763134/16516317/b695090c-3f77-11e6-8530-1827438e644b.PNG)

my project structure:
![str](https://cloud.githubusercontent.com/assets/3763134/16516346/e342e3e8-3f77-11e6-984d-dd08406617b3.PNG)

**Comment by kurisubrooks** [comment]
Try modifying your `APP_ICON` path variable to `path.join(__dirname, 'assets', 'img', 'icon.png')`

**Comment by epezhman** [comment]
@kurisubrooks Thanks for the comment, I changed it but still same behavior, not working in production

**Comment by kurisubrooks** [comment]
This is interesting, and rather unexpected behaviour. Because you're using Electron, is there no way you can call `new Notification()` from the Browser Process?

**Comment by epezhman** [comment]
@kurisubrooks Thanks, I used notification like below from my Browser Process and it's showing now the icon both on development and production, maybe I should switch to` Notification()` when I'm on windows, but I'm not sure if it's the best idea. 

I also tested my app on Ubuntu and the notification works without any problems (however on Ubuntu I don not use `asar `and I use `asar `only on windows, I have to use `asar `on windows otherwise my app throws exception while installing)

```
 var notification = new Notification(config.APP_NAME, {
            icon: config.APP_ICON,
            body: 'Test Notification'
        })

```

**Comment by kurisubrooks** [comment]
If the app throws an exception when not building an `asar` on Windows, i'd recommend you look into what's going wrong in the build process, probably something in the module you use to build for Windows, maybe issue a bug report with the module's maintainer.

Sorry I couldn't help with the issue at hand, but i'm glad we found a work around.
If you have any more questions, please let me know. 

Re-open the issue if you have any further problems.
