### ISSUE TITLE
Time option for notify-send

### ISSUE THREAD

**Issue by LaurensRietveld** [mikaelbr/node-notifier#128]
I am a bit confused by the notify-send configuration. The `README.md` shows that the the `time` option  should be used to define how long (in ms) the notification should be shown.
Assuming that the notify-send lib _does_ support  defining this duration [1], this option does not seem to be passed on as command-line argument. `expire-time` however _is_ passed on as command-line `time` argument (https://github.com/mikaelbr/node-notifier/blob/master/notifiers/notifysend.js#L70). 

Some humble suggestions:
- rename the undocumented `expire-time` option for notify-send to simply `time` 
- add a link the PPA from [1] to inform users how to use the version of notify-send that supports this time flag

[1] The `notify-send` tool does not support a duration, which the authors consider a 'design decision' rather than a bug (in this case, I find it both). Instead, this PPA (https://launchpad.net/~leolik/+archive/ubuntu/leolik) does support `notify-send` with the time flag.

**Comment by mikaelbr** [comment]
Will have to look into this. I've been following these docs when implementing the option schema: http://manpages.ubuntu.com/manpages/xenial/en/man1/notify-send.1.html which says it support expire-time.

**Comment by LaurensRietveld** [comment]
Fyi: an interesting thread about this notify-send bug/feature : https://bugs.launchpad.net/ubuntu/+source/notify-osd/+bug/390508

I'm away from the computer for 2 weeks, but if you need e.g. a dockerimage that reproduces this, let me know and I'll fetch one for you later this month

**Comment by mikaelbr** [comment]
Thanks! 👍  I'll check it out. Have a nice vacation (or at least time away from the computer).

**Comment by mikaelbr** [comment]
If I remember correctly, there's an error with passing surplus arguments to notify-send on Ubuntu, so just passing `time` in addition won't do. I think I'll mark this as a won't fix for now and maybe look more into it if there's a on going issue more reports.
