### ISSUE TITLE
I don't see notifications in fullscreen mode

### ISSUE THREAD

**Issue by melihovv** [mikaelbr/node-notifier#130]
When I turn WebStorm in fullscreen mode, I don't see notifications anymore. Maybe there is option for window priority or something similar to see notifications in fullscreen mode?
Windows 7 x64
My code 
```
import notifier from 'node-notifier';
...
notifier.notify({message: 'Webpack finished'});
...
```

**Comment by kurisubrooks** [comment]
I'm pretty sure this is a limitation of Windows 7. Windows 7 has no
Notifications API, so we have to use task bar bubbles. I'm unaware of any
options that would allow us to set priority to a bubble, because they're
much different to the notifications APIs in Windows 8+

**Comment by melihovv** [comment]
It is sadly. But thanks anyway.

**Comment by kurisubrooks** [comment]
Sorry we can't help. Blame Microsoft 😊
