### ISSUE TITLE
error received: TypeError: fn.apply is not a function

### ISSUE THREAD

**Issue by tamaker** [mikaelbr/node-notifier#132]
Im using the following and consistently get the error: 
```
TypeError: fn.apply is not a function
    at /usr/local/lib/node_modules/node-notifier/lib/utils.js:175:8
    at /usr/local/lib/node_modules/node-notifier/lib/utils.js:55:5
    at ChildProcess.exithandler (child_process.js:198:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

code I'm using that DOES successfully fire a notification on OSX:
```javascript
var notifier = require('/usr/local/lib/node_modules/node-notifier');
// String 
notifier.notify('Message');
                 
// Object 
notifier.notify({
    'title': 'My notification',
    'message': 'Hello, there!'
}, 2000);
```

immediately after the notification appears, the node.js http server instance crashes.

Im running node v6.2.2 on OSX 10.10.4

**Comment by positlabs** [comment]
What code are you running that fails?

**Comment by mikaelbr** [comment]
The problem here is the second argument when doing:

```
// Object 
notifier.notify({
    'title': 'My notification',
    'message': 'Hello, there!'
}, 2000);
```

See the [documentation](https://github.com/mikaelbr/node-notifier#cross-platform-advanced-usage), the second argument is a callback function, not a time delay.

Passing something other than a function here will cause a error. This probably should throw a typeerror with a descriptive text.

**Comment by schenkfab** [comment]
Hi @mikaelbr . I would like to give this a try.

**Comment by mikaelbr** [comment]
Perfect! Just let me know if you need any help getting started.

**Comment by schenkfab** [comment]
Thank you! I'll let you know if everything fails :+1:
