### ISSUE TITLE
Windows 8.1 Toaster icon is not showing

### ISSUE THREAD

**Issue by rico345100** [mikaelbr/node-notifier#133]
On my Windows 8.1, notifier.notify also doesn't work, so I used notifier.WindowsToaster().notify, it is working.
The main problem is icon is not showing up only Windows 8.1, not OSX. This is the code:

`
        const notifier = require('node-notifier');

```
    if(process.platform === 'win32') {
        new notifier.WindowsToaster().notify({
            title: arg.sender,
            message: arg.message,
            icon: path.join(__dirname, 'noti.png'),
            sound: true
        });
    }
    else {
        notifier.notify({
            title: arg.sender,
            message: arg.message,
            icon: path.join(__dirname, 'noti.png'),
            sound: true
        });
    }
```

`

I used absolute path as you can see: path.join(__dirname, 'noti.png'). I'm using Electron, and that image file is in "resources/app/noti.png". 

Also I really want to know that why notifier.notify not working on my Windows 8.1, but other people are working. Thanks.

**Comment by mikaelbr** [comment]
Hi. Have you tried without the icon? Does it work on Windows 8.1 without it? What version of node-notifier are you using?

**Comment by rico345100** [comment]
I removed icon, it works on Windows 8.1. I'm using 4.6.0.

**Comment by rico345100** [comment]
Well, no more question? Any solution please?

**Comment by mikaelbr** [comment]
I'm sorry, but I'm having a hard time understanding what the real problem is here. I think, maybe, something's lost in translation. Let me try to clarify:

- `notifier.WindowsToaster().notify` - Works on Windows with image
- `notifier.notify` *without* image - Works on OS X and on Windows
- `notifier.notify` *with* image - Works on OS X, but *not* on Windows. Notification is visible but no image

Correct?

Have you tried outside of electron? Does it work then? Do you get any errors? Try logging errors using:

```js
notifier.notify({ /* opts */ }, function (err, response) {
  console.log('Error:', err);
});
```

Have you tried other image formats? Does that change anything?

**Comment by rico345100** [comment]
Looks like I found solution. For development, I didn't packed my electron app's resources, and then It worked with image. Looks like this is happening after packaging electron resources. I will test some more about it and I will tell you if continues...

**Comment by kurisubrooks** [comment]
node-notifier, as well as a metric ton of other modules, have known issues with Electron's asar format. Refer to our README ([here](https://github.com/mikaelbr/node-notifier/#within-electron-packaging)) and let us know if this works, and how the icon goes.

**Comment by WilixLead** [comment]
I have equal problem. Just node-notifier can't use asar image resource.
I pack my app and exclude node-notifier binaries. Notification shows but without needed image (with default).
As possible solution, I think good idea add stream parser to notifier for use it like
icon: fs.readFileSync(MY_ICON_ARAR_PATH)

**Comment by mikaelbr** [comment]
I don't think reading file content would work when passing to vendors through execution. This seems to me as an issue with using electron and asar. Closing for now as a wontfix
