### ISSUE TITLE
Path of Icon not work in windows 10, packed by asar

### ISSUE THREAD

**Issue by gralance** [mikaelbr/node-notifier#137]
If asar is set to false , everything works fine, however, when asar is true
node-notifier can't resolve the path which contained asar file.

For example: 
file:///path/to/example.asar/static/test.png --> should get test.png from example.asar
This is not work in Windows, Mac works fine.
 
https://github.com/electron/asar

**Comment by kurisubrooks** [comment]
Due to the nature of asar files, node-notifier cannot run under asar.
asar binaries cannot have executables within. See [here](https://github.com/mikaelbr/node-notifier#within-electron-packaging) for more information.

**Comment by kurisubrooks** [comment]
Why not use [Electron's native notifications](http://electron.atom.io/docs/tutorial/desktop-environment-integration/#notifications-windows-linux-macos)?

**Comment by gralance** [comment]
Because it only works in Windows 10, thanks for your reply.
