### ISSUE TITLE
Update Lib to support ES Modules

### ISSUE THREAD

**Issue by kurisubrooks** [mikaelbr/node-notifier#139]
Update the module to support ECMAScript 2016 Module syntax.

Examples:
`import * as notifier from "node-notifier"`
`import NotificationCenter from "node-notifier"`
`import { NotificationCenter, Toaster } from "node-notifier"`
`import { NotificationCenter as mac, Toaster as windows } from "node-notifier"`

Reference:
http://www.2ality.com/2014/09/es6-modules-final.html
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/import

**Comment by mikaelbr** [comment]
Note: this will break usage pre node 4. Even if that will become unsupported many will still use it, I don't know if it is right for us to just break for many potential users. Also, one of main advantages with new module syntax is statical analysis and possible tree shaking/optimizations which doesn't really apply in the same manner in node. So i dont really see a good reason why we would do this?

I think there's scheduled a meeting in tc39 about node module resolving, so maybe there will be something comming out of that, but as of now I don't think converting to es2015 modules is the righ move. What do you think?

**Comment by kurisubrooks** [comment]
How about having a new branch of node-notifier that's maintained for ES6?
This branch could also make use of SnoreToast (proposed in #134), and we could maintain the current branch as "LTS", keeping Toast, as to make sure we're not breaking people's code as well.

**Comment by mikaelbr** [comment]
I honestly don't see any value for doing this at this point. [Module loader](https://github.com/whatwg/loader) as far as I can see isn't ready yet for Node. And even if someone is using transpiling for supporting the module syntax the current approach will work.

This is where JS in the frontend and on the backend differ. I see the value for using es2015 statically analysable module syntax on the frontend at the current point in time, but I don't think still there is a reason to make a transition for node packages. It really just don't add any value.

**Comment by kurisubrooks** [comment]
Alrighty, 'twas just an idea.
More and more modules are moving to the new format so I thought we'd might want to make the same decision aswell.

Maybe we can look into this again in the future.

**Comment by mikaelbr** [comment]
Sorry, didn't mean to sound aggressive in any way. 🐙 It is definitely something we can look into more in the future when the module loading strategies of Node has settled and there is a proper way to do it. But, there is also a way to do the same thing as of now:

Instead of
```js
import * as notifier from "node-notifier"
import NotificationCenter from "node-notifier"
import { NotificationCenter, Toaster } from "node-notifier"
import { NotificationCenter as mac, Toaster as windows } from "node-notifier"
```

One can do

```js
const notifier = require('node-notifier');
const { NotifySend } = require('node-notifier');
const { NotificationCenter, WindowsToaster } = require('node-notifier');
const { NotificationCenter: mac, WindowsToaster: windows } = require('node-notifier');
```

**Comment by kurisubrooks** [comment]
Oh no, I didn't find it aggressive at all.
Didn't know this way of importing modules could be used. Neat!

**Comment by sJJdGG** [comment]
@mikaelbr What do you think of supporting it now?

It's landed in stable nodejs and lots of community packages already support it too
