### ISSUE TITLE
Installation of node-notifer failing on dependency marked-terminal

### ISSUE THREAD

**Issue by sdotson** [mikaelbr/node-notifier#140]
Hello,

I'm trying to use node-notifier in my project by using `npm install --save node-notifier` but it is failing with the following message:
```
npm ERR! node v4.2.1
npm ERR! npm  v2.15.9
npm ERR! code ETARGET
npm ERR! notarget No compatible version found: marked-terminal@'>=1.6.2 <2.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","1.0.0","1.1.0","1.1.1","1.1.2","1.1.3","1.2.0","1.3.0","1.4.0","1.5.0","1.6.0","1.6.1"]
```

**Comment by kurisubrooks** [comment]
Hi, it looks to me like `marked-terminal` has a valid `1.6.2` target, but it seems your current version of npm won't detect it.

As an attempt to fix this, could you try upgrading your version of npm for me? `sudo npm install npm -g`. Once npm is upgraded, please try `npm install node-notifier --save` again and let us know!

**Comment by sdotson** [comment]
I just figured out that this is a problem with our corporate npm registry. When I switch to https://registry.npmjs.org/ everything is good. Things install just fine. Ugh. Closing. 

Thank you for your prompt response.
