### ISSUE TITLE
Support for macOS Notification Actions, Reply & Timeout from terminal-notifier 1.7.0

### ISSUE THREAD

**Issue by kurisubrooks** [mikaelbr/node-notifier#141]
Added in a recent release of terminal-notifier, it now gives the capability to customise macOS Notifications even further than before. 

Notification Timeouts (`-timeout VALUE`), closes the Notification after a set number of seconds.
Notification Actions (`-actions VALUE1,VALUE2`), customise the notification's action titles
Notification Reply (`-reply VALUE`), get replies through the notification, value is used as a text placeholder
Notification Response as JSON (`-json`), outputs the notification's response as JSON

Git diff: https://github.com/julienXX/terminal-notifier/commit/67422e7520bc35d36b9e81487e9632bf9aa10d3a

**Comment by mikaelbr** [comment]
This should be out in master now. It's difficult to verify that all is as before (not breaking) as we don't have integration tests with the actual vendors (would be difficult to do cross-platform and on CI-systems). So it would be great if as many as possible can verify that it all works as before, but just with additional functionality.

**Comment by mikaelbr** [comment]
This is implemented now.
