### ISSUE TITLE
Click handler issue

### ISSUE THREAD

**Issue by arkakkar** [mikaelbr/node-notifier#143]
Click handler triggered when notification is clicked while in view. After the notification slides out, click handler not being triggered from notification center.

**Comment by kurisubrooks** [comment]
I don't think there's any way to detect click events once the program has finished being run.
When it's added to the Notification Center, it's outside of the program's control.

Click events can only be received while the program is still running, and the program closes once the Notification is closed, aka, moved off screen. 

I don't think we'll mark this as a bug, as it's more a technical limitation.

**Comment by arkakkar** [comment]
Would there be some other way to do that, something for macOS since apps like slack already do it and there would be no use of notifications if a user isn't able to use it through the notification center.

**Comment by kurisubrooks** [comment]
If you're already using electron, why don't you use Electron's built-in Notification APIs? 
http://electron.atom.io/docs/tutorial/desktop-environment-integration/#notifications-windows-linux-macos

**Comment by kurisubrooks** [comment]
Also just for reference, Slack does not use Electron for macOS. They do use it for Windows and Linux however.

**Comment by mikaelbr** [comment]
(AFIK, the beta for macOS is also Electron: https://slack.com/beta/osx)

I don't know if I understand the problem her. Node applications using `node-notifier` are designed to halt and wait until the notification is gone if you provide the notifiaction option with the `wait: true` option:

```js
notification.notify({
  message: 'Hello',
  wait: true
}, function () {
  console.log('Clicked and waited');
});
```

I'm I misunderstanding this?

**Comment by kurisubrooks** [comment]
He wants to be able to detect click events while the Notification is in the Notification Center. AKA The slide over. 


![image](https://cloud.githubusercontent.com/assets/6291467/19469925/3031df50-9569-11e6-8cc5-122398a17809.png)

**Comment by mikaelbr** [comment]
Ah. Right. Thanks for the explanation. As far as I know that's not possible. Other than maybe adding a custom app schema (`myApp://foo?some-data=here`) and using the `open` option.

**Comment by arkakkar** [comment]
There are a few issues with the electron Notification api it clears all notifications from notification center even on clicking just 1 of the notifications. Also on closing the app it removes all notifications from the notification center.
I guess everything is happening in the renderer process so even if notifications persists I would be able to catch the click when the app is closed.
Can we get around these issues in electron in some way
Also the terminal notifier used with the node-notifier lists we can open the app when passing in the correct bundle id
