### ISSUE TITLE
Mac not working from background (PM2)

### ISSUE THREAD

**Issue by svrooij** [mikaelbr/node-notifier#148]
I'm trying to send notifications from my mqtt server with my node app [node-mqtt-notification](https://github.com/svrooij/node-mqtt-notification) which works great (but the way), until I start the program with [PM2](http://pm2.keymetrics.io/docs/usage/quick-start/) (to run in the background and on system reboot).

According to the logs the message I'm sending to my computer gets received, but it won't show any notification. Could you point me in the right direction on how to solve this issue?

- macOS Sierra
- Node v7.2.1

**Comment by kurisubrooks** [comment]
Hmm, we haven't tested this under pm2.
Are there any errors or debug that are outputted at all if you listen for them?

**Comment by adams-family** [comment]
I experience the same thing. I installed my code using "node-mac" [https://github.com/coreybutler/node-mac] as a **lunchd** service and if the notification script is invoked from a service then it does not work.

I can post some sample code if you need it.

**Comment by mikaelbr** [comment]
It seems to work fine with me behind pm2? Check out: https://www.youtube.com/watch?v=nj51wuiOrVU
