### ISSUE TITLE
Terminal Icon still shows up after replacing the icon image

### ISSUE THREAD

**Issue by Hoyiki** [mikaelbr/node-notifier#150]
![screen shot 2017-01-11 at 9 41 38 pm](https://cloud.githubusercontent.com/assets/11425091/21850698/cc5c99d6-d846-11e6-8736-ca3f27bfe3fc.png)
Hi,
When I replace the icon image, a smaller terminal icon shows at the beginning of the title. Any ways to remove it? Thank you!

**Comment by kurisubrooks** [comment]
Please refer to issue https://github.com/mikaelbr/node-notifier/issues/71#issuecomment-147209781
