### ISSUE TITLE
Mac: 'wait' option isn't respected

### ISSUE THREAD

**Issue by doronsever** [mikaelbr/node-notifier#152]
From what i understand from the docs, If i set `wait: true`, the notification will wait until a user action.
But what really happen is that the notification is closed after 5 seconds and a "timeout" event is been fired..
This makes it a problem if i want to set `replay: true` either because the 'timeout' event will be fired after 5 seconds and the 'reply' event won't fire.

**Comment by mikaelbr** [comment]
From https://github.com/mikaelbr/node-notifier/issues/147#issuecomment-274277899:
> I think maybe there's some misunderstanding around what wait does. wait doesn't make a sticky notification, it forces things like terminal-notifier til wait until response is returned. Without wait, it will just "fire and forget" but with wait it waits until timeout or user interaction.

**Comment by doronsever** [comment]
If any one need some help please take a look at:
https://github.com/mikaelbr/node-notifier/issues/147

**Comment by kevinelliott** [comment]
@mikaelbr Yes, `wait` is totally misunderstood. Now reading that I understand it. I think the documentation should be updated to reflect that, and also perhaps renaming the option to something like `waitForNotifierProcess` or similar to be more explicit. I know that it's longer and not as succinct as `wait`, but `wait` is truly confusing and does not given insight into what it is for. I think many of us immediately think `let the notification stay on the screen until the user interacts with it`.
