### ISSUE TITLE
Remove SnoreToast message from notification in Windows 10

### ISSUE THREAD

**Issue by albertvazquezm** [mikaelbr/node-notifier#154]
Hi,

How can we remove the SnoreToast message that appears on the notification? Is there any way to replace it?

Thanks.

**Comment by kurisubrooks** [comment]
I'm unfamiliar with Windows as I work primarily on macOS, but i'm guessing you're implying it says `SnoreToast` somewhere on the Notification? If so, i'm going to guess Windows handles this similarly to macOS, in which case it says SnoreToast because that is the referring app (.exe) that is calling the notification. I know of a way to override this on macOS but not on Windows unfortunately. Could you give me some more information, perhaps a screenshot so I can try to help you better?

**Comment by mikaelbr** [comment]
@kurisubrooks The example in the readme is updated to reflect the latest changes :) ![Toast](https://raw.githubusercontent.com/mikaelbr/node-notifier/master/example/windows.png)

@albertvazquezm I'm afraid that might be difficult without forking [snoretoast](https://github.com/KDE/snoretoast) and building your own version of it. If you look into doing that, `node-notifier` supports custom paths for your executable. See the readme. But I'd suggest to post an issue on [snoretoast](https://github.com/KDE/snoretoast). Other than that it's little we kan do, I'm afraid.

**Comment by mikaelbr** [comment]
Maybe this is something: https://github.com/KDE/snoretoast/blob/master/src/snoretoasts.cpp#L313
I don't know.

**Comment by piotr-cz** [comment]
Moreover this text is shown only when using _contentImage_ option.
It would be helpful to utilize that space for the subtitle option which ATM isn't supported by any of the windows notifiers.

Unfortunately [snoretoast repo](https://github.com/KDE/snoretoast) doesn't have Issues enabled

**Comment by mikaelbr** [comment]
It might make sense to do a maintained fork of the snoretoast repo.

**Comment by piotr-cz** [comment]
I won't volunteer as I'm not good in C++.
But it's definitely possible, Windows 10 system notifications have icons and don't show referring app

**Comment by VasiliyIsaichkin** [comment]
@mikaelbr https://github.com/KDE/snoretoast/blob/master/src/snoretoasts.cpp#L313 incorrect - its just debug XML and now used in release.
For cutomize this string you need just set -appID param for SnoreToast.exe 

For example:
`SnoreToast.exe -p C:\Projects\testSnoreToast\coulson.png -m Hello -t World -s Notification.Default -appID Wow-wow`

![170311-055928-kwav96ltztcgqt7](https://cloud.githubusercontent.com/assets/1153891/23819991/fefa674a-061f-11e7-9009-f4e3c1e1537f.png)

**Comment by VasiliyIsaichkin** [comment]
For disable it, also we can add to options `appID : '\t'`

**Comment by piotr-cz** [comment]
@VasiliyIsaichkin using `'\t'` prints out `\t` so I guess it's better to use `" "`.

Whe used `appId` option it's indeed possible to set third line of the notification as long as it's used together with the `image` option. When there is no image specified, there is no appId displayed either.

Anyway IMHO it's still better then having _SnoreToast_ text

**Comment by mikaelbr** [comment]
This should be fixed now, but maybe caused some other issues in the process. But as far as this issue goes, I think we can close it.

**Comment by mikkelsiggaard** [comment]
@mikaelbr 
I'm running 5.2.1 on Win10 and have tried the possibilities above - but it doesn't work. 

`title: 'Admin panel',`
 `message: 'Server is provisioned',`
`icon: path.join(__dirname, 'build','logo.png'), `
`sound: true,`
`appId: 'This message is not displayed'`

But:
![capture](https://user-images.githubusercontent.com/23178730/40117596-ab456568-5917-11e8-888b-13acff873a1c.PNG)

And as others have said, when I remove the icon the subtext "SnoreToast" is removed.

What is the correct practise here?

**Comment by MikeKovarik** [comment]
+1 on this. I've been scratching my head to customize it for a long time. Nothing from this issue (`appId: '\t'`, `appId: " "`, `appId: 'anything else'`) works for me on v5.2.1. In fact if i put in any string it displays the SnoreToast, except for the `\t` in which case the notification is not displayed at all.

**Comment by pmk65** [comment]
I got it working like this:
SnoreToast.exe -install "%APPDATA%\Microsoft\Windows\Start Menu\Programs\WeBuilder.lnk" "%PROGRAMFILES%\WeBuilder 2018\webuild.exe" "WeBuilder"

SnoreToast.exe -t "title" -m "message" -p "webuilder.ico" -appID "WeBuilder"

**Comment by eebanos** [comment]
Just follow this steps: https://www.howtogeek.com/219703/how-to-disable-notification-sounds-in-windows-10/

**Comment by AbsSimon** [comment]
@eebanos thank you, perfect solution

**Comment by 9aram** [comment]
@pmk65 Hi, your solution works at cmd when i typed all of your code. but when I back to code 
```
  const notifier = require('node-notifier');
        // Object
        notifier.notify({
            title  : 'Admin panel',
            message: 'Party message',
             icon   : './facebook.png',
            appId  : ' ss'
        })
```
It still shows SnoreToast

**Comment by pmk65** [comment]
@9aram The 1st line in my example registers the appid "Webuilder". You need to do the same to register the appid " ss" you are using. (Not sure if it can contain a space as yours do) 

It will create a shortcut file in %APPDATA%\Microsoft\Windows\Start Menu\Programs\ named "Webuilder.lnk". Just change that and the app to point at your code.

**Comment by BluFenix00** [comment]
i could replace the SnoreToast text setting the appID but the icon is very small

**Comment by newCodeRunner** [comment]
To anyone stumbling upon this,

the prop key is 'appID' not 'appId'. Correct this and it works perfectly.

Windows 10
Node 12.13
Electron 8.1.1
