### ISSUE TITLE
New process created for each notification

### ISSUE THREAD

**Issue by jasonpoe** [mikaelbr/node-notifier#156]
A new process is being created for each notification which can bring your OS to a halt.  If you send multiple notifications in quick succession, you end up with a number of processes running:

<img width="687" alt="screen shot 2017-02-27 at 9 23 13 am" src="https://cloud.githubusercontent.com/assets/1102179/23367264/3dec8bfe-fccf-11e6-907a-a61c0db0ef7e.png">

Usage:
```javascript
const nodeNotifier = require('node-notifier');
nodeNotifier.notify({
  title: 'Title',
  message: 'Message content',
  sound: '/path/to/asset/'
  contentImage: '/path/to/image',
  actions: 'View'
}, (error, responseType, metadata) => this.onNotificationAction(error, responseType, metadata));
```

Using node-notifier version 5.0.2

**Comment by B3rry** [comment]
👍

**Comment by mikaelbr** [comment]
Hi. This is the way the implementation work, and I don't think you'll be able to get this to share processes. Under the hood node-notifier uses native macOS implementation of notification and a child process to execute it.

There's been an issue with the macOS implementation where it's not timed out properly and it [is being worked on](https://github.com/julienXX/terminal-notifier/issues/173#issuecomment-287628770). To add a temporary workaround for this, I added a second manual timeout from node-notifiers end which kills the child processes when they don't quit them self. Please check out the latest node-notifier and see if this is still an issue.

**Comment by mikaelbr** [comment]
The latest terminal-notifier (in master) shouldn't have the memory leak problem as seen. So I think this is good to close.
