### ISSUE TITLE
Ability to choose between banner and alert notifications

### ISSUE THREAD

**Issue by Dexwell** [mikaelbr/node-notifier#164]
Right now all notifications on macOS are being posted as alert-style notifications, which means the notifications always show buttons and stay onscreen until dismissed. This should only happen for important events. It should be possible to post a banner notification without having the user change the app's notification permissions in System Preferences.

**Comment by mikaelbr** [comment]
I think this is something that is needed from upstream in https://github.com/julienXX/terminal-notifier
