### ISSUE TITLE
Custom sound for notification on macOS doesn't seem to work

### ISSUE THREAD

**Issue by yliaho** [mikaelbr/node-notifier#166]
I'm trying to get a custom wav playing for the `sound` property, but it just defaults to the default bell sound. Are there some specific requirements for the audio file to work or..? Alternatively, if I could get an example of how to reference the audio file, that'd be sweet! (in case I'm doing it wrong – excuse my ignorance)  
  
Thanks in advance!

**Comment by kurisubrooks** [comment]
From the README:
> Sound can be one of these: `Basso`, `Blow`, `Bottle`, `Frog`, `Funk`, `Glass`, `Hero`, `Morse`, `Ping`, `Pop`, `Purr`, `Sosumi`, `Submarine`, `Tink`. If sound is simply `true`, `Bottle` is used.

In order to use a custom sound, you'll have to copy the audio file to `~/Library/Sounds`, then you can use the name of the file as the audio string. e.g. `customFile` rather than including the extension in the name. 

I've used this method before with `.mp3` files but I cannot confirm that a `.wav` file will work.

**Comment by Yliaho** [comment]
Alright, thank you for a quick response! That makes sense.  
  
[This](https://github.com/mikaelbr/node-notifier#all-notification-options-with-their-defaults) section said to use string for location of the sound file which I kept trying over and over but it just simply didn't work.

**Comment by kurisubrooks** [comment]
I think it needs to be part of the system directory, rather than the location of the file. Sorry ~

**Comment by Alxmerino** [comment]
I am currently having the same issue, does this mean that you cannot package this as an electron app with notifications?

**Comment by voveson** [comment]
I'm also trying to use this in an electron app to customize the notification sound. Is this possible?

**Comment by rishabh1403** [comment]
I had the same problem, I switched off the default notifer sound by setting sound to false in options, and played custom sound using Javascript Audio Api @voveson @Alxmerino

**Comment by kurisubrooks** [comment]
You can use custom sounds on macOS, but the process is a bit more difficult. On launch of your app, you need to copy/move the audio files to the user's `~/Library/Sounds/`, then you'll be able to use the file's name in the "sound" field.

**Comment by Harvzor** [comment]
@rishabh1403 Thanks for the idea.

## How to play a sound with Node (tested on Windows 10)

It seems that Node generally can't play audio in any easy way on it's own. You may need to download an extra program to play a sound.

I used `play-sound` with `mpv` to play a `.wav` file. `play-sound` is the most popular NPM package for playing sounds, based on the number of downloads it has. `mpv` is a fork of `mplayer`.

Install `play-sound: `npm install play-sound`
Install MPV: https://mpv.io/installation/

The code:
```
// I recommend not installing MPV to start with and just leaving the opts blank to see if it can successfully play something.
var player = require('play-sound')(opts = { player: 'mpv' });

notifier.notify({
    title: 'Title',
    message: 'Message',
    // Disable the sound!
    sound: false
});

player.play(__dirname + '\\path\\to\\your\\file.wav', (err) => {
    if (err) throw err
});
```

Hope someone finds this useful (and that it's not too off topic).
