### ISSUE TITLE
Url not opening on click?

### ISSUE THREAD

**Issue by sparcut** [mikaelbr/node-notifier#168]
Links are just not opening when notification is clicked. Currently testing on Windows 10 Home. Notifier parameters are set as follows:

`notifier.notify({
	title: 'Notification',
	message: 'Hello World',
	sound: true,
	open: 'https://www.google.com',
	wait: true
});`

**Comment by mikaelbr** [comment]
Hi @sparcut. I'm sorry to say Windows toasts doesn't have that feature. See complete feature set for Windows toasts here: https://github.com/mikaelbr/node-notifier#usage-windowstoaster

You could add a activation listener and trigger open from node. Something like:

```js
var open = require('open');

notifier.notify({
  title: 'Notification',
  message: 'Hello World',
  sound: true,
  wait: true
}, function () {
  open('https://www.google.com');
});
```

Where open is installed using `npm install --save open` or the like.

**Comment by sparcut** [comment]
@mikaelbr Darn, I had a feeling that was the case.

While I was waiting for a response on this, I thought of doing the same thing you suggested but instead with a similar package, `opn`. It works, but the callback is run no matter the action taken on the notification, is it stable to check the response of the callback... the sentence? Since it doesn't seem to be a parameter just a sentence like "the toast has timed out" or "the user clicked on the toast.". Though from the package README, this seems the way that is suggested (below).

> To be able to listen for response (like activation/clicked), you have to define a timeout.

**Comment by mikaelbr** [comment]
Callbacks are triggered on timeout and activation, but you can explicitly set an on click event:

```
notifier.on('click', function (notifierObject, options) {
  // Triggers if `wait: true` and user clicks notification
});
```

**Comment by sparcut** [comment]
I'm going to assume doing something like this isn't cross platform friendly?

````javascript
notifier.on('click', function(notifyObject, opt) {
  opn(opt.open);
});
````

Since platforms that support the standard `open` option would open it twice.

So, is there an acceptable practice to add custom options to the options parameter (`opt`) like below?

````javascript
notifier.notify({
  title: 'Notification',
  message: 'Hello World',
  sound: true,
  wait: true,
  customOptions: 'xyz'
});
````

**Comment by mikaelbr** [comment]
It is cross platform. See open docs

**Comment by sparcut** [comment]
Sorry, I meant the first example in my last post. I was unsure if using the open option from the original `notifier.notify()` in the explicit on click would cause (on platforms that support the `open` option) two instances of the link to open.
