### ISSUE TITLE
"toast" string  at the bottom of my notification message

### ISSUE THREAD

**Issue by LoloSh** [mikaelbr/node-notifier#170]
I'm working on a NodeJS/Electron/Angular app and I am using the node-notifier module. Every things work correctly but at the bottom of  my notification message I have an inappropriate "toast" string.
It only happens when I use the "icon" property. 
What should I do to remove that string ? 
Thanks in advance.

PS : My operating system is Windows 10.

**Comment by LoloSh** [comment]
![bug](https://cloud.githubusercontent.com/assets/19708204/25727622/e8b0704c-30ef-11e7-88f7-4ba999c3cd78.png)

**Comment by mikaelbr** [comment]
See section on `appId` on https://github.com/mikaelbr/node-notifier#usage-windowstoaster

**Comment by wubing0324** [comment]
i read the link https://github.com/mikaelbr/node-notifier#usage-windowstoaster，but it didnt say how to reslove this question！

**Comment by wubing0324** [comment]
> See section on `appId` on https://github.com/mikaelbr/node-notifier#usage-windowstoaster

i read the link https://github.com/mikaelbr/node-notifier#usage-windowstoaster，but it didnt say how to reslove this question！
