### ISSUE TITLE
Default icon moves into title when using custom icon

### ISSUE THREAD

**Issue by naheller** [mikaelbr/node-notifier#175]
_This issue occurs on MacOS_

Here is the notification:
![notification](https://cloud.githubusercontent.com/assets/18204925/26375742/f185525e-3fbe-11e7-8af2-68ce19498e69.png)

And the code that builds it:
![screen shot 2017-05-23 at 1 51 46 pm](https://cloud.githubusercontent.com/assets/18204925/26375789/19ec2722-3fbf-11e7-80ee-e2889d9df493.png)

How can I get rid of the little black box icon? Thanks!

**Comment by mikaelbr** [comment]
Hi. For the current version of node-notifier check out this text in the readme: https://github.com/mikaelbr/node-notifier#custom-icon-without-terminal-icon-on-macos

Note: This is subject (possibly) to change in the next major release due to changes in dependency https://github.com/julienXX/terminal-notifier.

**Comment by naheller** [comment]
Thanks. Looks like a 15 step process, according to the linked issue #71. Will future versions of node-notifier be able to address this?

**Comment by GeorgeBgk** [comment]
Here's a quick guide how to do it. (If you don't have an ICNS file, here's a [converter](https://iconverticons.com/online/))

1. Navigate to `node_modules/node-notifier/vendor`
2. Rename your custom icon into `Terminal.icns`
3. Right-click `terminal-notifier` file and click `Show Package Contents`
4. Navigate to `Contents/Resources`
5. Replace `Terminal.icns` file with your own
![ezgif-2-637e763ed9](https://cloud.githubusercontent.com/assets/11464592/26460221/a709ee96-4181-11e7-800e-1f692a57a2e4.gif)

Here you go! Hope this helps.

**Comment by naheller** [comment]
@GeorgeBgk Hey there, thanks for your reply! If I make the edits you specified, will they remain in place when other people install and use the app? Won't the package.json file just install a fresh copy of node-notifier upon `npm install`?

**Comment by kurisubrooks** [comment]
You'll have to distribute your node-notifier binary. Add it to a `lib/` folder or something, then commit it. You can use that explicit binary like so:

```js
const { NotificationCenter } = require('node-notifier');

const notification = new NotificationCenter({
    customPath: path.join(__dirname, 'lib', 'notifier.app', 'Contents', 'MacOS', 'terminal-notifier')
});
```

**Comment by GeorgeBgk** [comment]
@naheller Yes, it will, but if you use electron packager, your existing node-notifier will be kept.
Also, check that out: 
You can move the binary out of node_modules and specify path to it
`var notifier = new NotificationCenter({
  withFallback: false, 
  customPath: void 0 // Replace with path
});`
