### ISSUE TITLE
on click not firing for multiple notifications

### ISSUE THREAD

**Issue by rishabh1403** [mikaelbr/node-notifier#177]
I have been using node-notifier with electronJs to send desktop notification. It was working fine till we had single notification. Recently we are getting frequent notifications , while notifier does notify those notifications in quick sessions but the click handler does not work all the time as expected, sometimes it just works for the first notification, sometimes just for the last notification and other times just does not work at all. Here is my code,

    notifier.on('click', (notifierObject, options) => {

        console.log("on click firing"); 

        // let window = BrowserWindow.getFocusedWindow();

        win.restore();

        win.maximize();

    });

    let showNotification = args => {
        notifier.notify({
            title: args.title,
            message: args.message,
            timeout: 5,
            icon: './favicon.png',
            sound: false,
            wait: false
        }, (err, response) => {});
    };

showNotification function is being called multiple times based on some events. is there any way to listen click events on all the notifications ?
Thanks for this awesome module.

**Comment by mikaelbr** [comment]
Hi! So, the `notifier.on('click'` isn't triggered all the time? How about the callback from notifier.notify? Does it give you any feedback when clicking?

**Comment by rishabh1403** [comment]
Callbacks were being called, but some how onClick were not being called for all the notifications. Well I went with showing single notification at a time and clubbing data when I have multiple notifications, so eventually It will only show 1 notification. Thanks
