### ISSUE TITLE
waiting is not working for windows 10

### ISSUE THREAD

**Issue by victorcid** [mikaelbr/node-notifier#189]
hi i've been triign the example code and some bariants but i can't make it work the notifications fade in about 10 seconds no matter what

const notifier = require('node-notifier');
const path = require('path');

notifier.notify({
  title: 'My awesome title',
  message: 'Hello from node, Mr. User!',
  icon: path.join(__dirname, 'coulson.jpg'), // Absolute path (doesn't work on balloons)
  sound: true, // Only Notification Center or Windows Toasters
  wait: true, // Wait with callback, until user action is taken against notification
  time:1000000
}, function (err, response) {
  // Response is response from notification
});

**Comment by mikaelbr** [comment]
See specific documentation for Windows Toasters: https://github.com/mikaelbr/node-notifier#usage-windowstoaster. Not all systems support all features I'm afraid, so something might be supported on macOS but not on Windows. Windows doesn't allow for specific timeout.
