### ISSUE TITLE
Stack multiple notifications

### ISSUE THREAD

**Issue by mhkeller** [mikaelbr/node-notifier#194]
When I run the below example from the readme on macOS 10.12.6, the second notification almost immediately replaces the first. Is there a way to get these to stack as two separate notifications?

```js
const notifier = require('node-notifier');
// String
notifier.notify('Message');

// Object
notifier.notify({
  'title': 'My notification',
  'message': 'Hello, there!'
});
```

**Comment by tylerdmace** [comment]
Play with the settings in Notification Center. If you chose the 'Alerts' alert style instead of 'Banners' for terminal-notifier, you'll get the behavior you'd expect. Downside is that they have to be manually closed, I believe.

**Comment by mhkeller** [comment]
Hm, no luck. Even setting `wait: true` doesn't seem to do it.

**Comment by mhkeller** [comment]
Actually, this works if installing from `master` branch as opposed to the version on npm. FWIW it works for me both on 'Banners' and 'Alerts' in the MacOs notification preferences.

Depends on https://github.com/mikaelbr/node-notifier/issues/198

**Comment by mhkeller** [comment]
Correction: @tylerdmace is correct. I was setting the alert style for iTerm and not for terminal notifier as he wrote.
