### ISSUE TITLE
Can close or actions button always show in the notification？

### ISSUE THREAD

**Issue by noinflation** [mikaelbr/node-notifier#195]
When I set closeLabel or actions options, I found the button only showing after I hover the notification, is there any way to show the button all the time ?

**Comment by mikaelbr** [comment]
AFAIK this is intended behaviour of macOS Notification Center. Don't know if there's anything we can do.

**Comment by philwolstenholme** [comment]
If `terminal-notifier` is set to use the 'Alerts' style in the macOS preferences then the button will be permanently visible:

<img width="673" alt="Screen Shot 2019-03-13 at 23 39 21" src="https://user-images.githubusercontent.com/6339853/54321489-5529a580-45e9-11e9-9add-a1a5c6c23573.png">

<img width="407" alt="Screen Shot 2019-03-13 at 23 39 46" src="https://user-images.githubusercontent.com/6339853/54321492-58bd2c80-45e9-11e9-9653-662d5a7eaef3.png">
