### ISSUE TITLE
Should use logical OR instead of AND

### ISSUE THREAD

**Issue by MayGo** [mikaelbr/node-notifier#201]
https://github.com/mikaelbr/node-notifier/blob/5e39a9098cd897520878f022c265af97fe73fd68/notifiers/toaster.js#L76

**Comment by mikaelbr** [comment]
Hi! I don't think so. This shows an error when both close and message is undefined. If it was an or, it would show error unless both are set.

**Comment by MayGo** [comment]
Read this code couple of times before. And your right.
I had an error in my application "options.message.replace is not a function". I am sure i have made a programming error somewhere with using node-notifier.  Thought, this was the place it should catch if message is missing. sorry.

**Comment by mikaelbr** [comment]
Sounds like you might have passed in a function or something not a string.

**Comment by MayGo** [comment]
yes, passed error object as message instead error string.
tnx
