### ISSUE TITLE
Can I custom define the notifier location?

### ISSUE THREAD

**Issue by dengyaolong** [mikaelbr/node-notifier#204]
I want to make the notifier alert at my custom location . like given a point(x,y) and alert at this point.

because always alert on right side (on mac) will block some information.

**Comment by mikaelbr** [comment]
I'm afraid this is outside node-notifiers control, or anything really. AFAIK, macOS always show the notifications at the same location.

<img width="642" alt="screen shot 2017-10-16 at 11 56 48" src="https://user-images.githubusercontent.com/606374/31606344-1d3fe798-b269-11e7-985a-2409be57a67e.png">
