### ISSUE TITLE
New terminal-notifier version

### ISSUE THREAD

**Issue by julienXX** [mikaelbr/node-notifier#211]
Hello,
I just released terminal-notifier 2.0.0 which has some large changes, I figured you might be interested.
https://github.com/julienXX/terminal-notifier/releases/tag/2.0.0

Cheers,
Julien

**Comment by mikaelbr** [comment]
Thanks! Looks like I'll have to change to `alerter` to still support input types

**Comment by julienXX** [comment]
Just so you know alerter will support `-reply`, `-actions, `-timeout`, `and `-json` but in a "blocking" way ie. waiting for user input.

**Comment by mikaelbr** [comment]
I think the best is to use 1.7.2 (with fixed memory leak for now). This won't break node-notifier existing use (v1.8.0 has different way of setting icon).

@julienXX Would you say there's a reason to use alerter over v1.7.2?

**Comment by julienXX** [comment]
@mikaelbr Until Alerter has some new features not in 1.7.2 I think you can stay on 1.7.2. Also Alerter uses the same way of setting an icon as it was in 1.8.0. But Alerter is just an executable and not a Bundle which may be useful to you at some point.

**Comment by mikaelbr** [comment]
Thanks for the swift reply. You are awesome 🎉
