### ISSUE TITLE
First notification not displaying on Windows 7

### ISSUE THREAD

**Issue by kblum** [mikaelbr/node-notifier#213]
I am using node-notifier in an Electron application. I am experiencing an issue where the first notification after the application launches does not display a taskbar balloon on Windows 7 (64-bit). The taskbar balloon does display for any notifications triggered after the first. This is encountered each time that the application launches. There are no errors or any other output logged to the console.

I am using version 4.6.1 of node-notifier but have also tested against version 5.1.2 and the behaviour is the same. The machine does not have Growl installed.

I have managed to implement a workaround for the time being by triggering a notification as soon as the application launches. This launch notification does not display and ensures that the first proper notification that the application receives does display correctly.

**Comment by mikaelbr** [comment]
Have you tried running the notifu tool directly first time and see what type of output there is?

**Comment by kblum** [comment]
Running the notifu executable included in `node-notifier\vendor\notifu` from the command prompt as `notifu.exe /m "Test Message"` does show the message the first time (and every time after that). No output is written to the console.

**Comment by tbanik** [comment]
Same issue still happening on Win10(64) in November 2019
