### ISSUE TITLE
Can't package with pkg module

### ISSUE THREAD

**Issue by EasonWang01** [mikaelbr/node-notifier#220]
It will result then following
```
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  ..\node_modules\node-notifier\vendor\notifu\notifu.exe
  path-to-executable/notifier/notifu.exe
```

OS:windows 10

**Comment by stevenwhitespacesystems** [comment]
Not sure for Windows as I haven't got around to it yet but you usually have to copy that .exe file to the folder where your pkg executable is built.

i.e. copy `notifu.exe` to `path-to-executable/notifier/notifu.exe`

For any Mac user who got here, it was slightly different and PKG wasn't totally clear.

```
> Warning Cannot include file %1 into executable.
The file must be distributed with executable as %2.
node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS/terminal-notifier
path-to-executable/notifier/terminal-notifier
```

You copy the `terminal-notifier` executable to the location like it states but you also need to copy the following files too the same location

```
- node_modules/node-notifier/vendor/terminal-notifier.app/Contents/Info.plist
- node_modules/node-notifier/vendor/terminal-notifier.app/Contents/Resources/en.lproj/MainMenu.nib
```

So in the end you should have the following structure at your build folder.

```
- path-to-executable/app
- path-to-executable/notifier/terminal-notifier
- path-to-executable/notifer/Info.plist
- path-to-executable/notifier/MainMenu.nib
```
Doing the above worked for me and executed the notification from the built pkg file.

**Comment by mikaelbr** [comment]
Thanks! Added this issue to the readme

**Comment by normen** [comment]
This MacOS workaround doesn't seem to work (anymore). I copy the terminal-notifier executable, Info.plist and MainMenu.nib to path-to-executable/notifier/* but my own executable created by pkg doesn't seem to be able to find them.

There is no notification issued and no error message appearing when running my pkg-created executable, when running the application using "node index.js" notifications are appearing.

OS: MacOS 10.14.6
Node: 12.41.1

**Comment by PabloWestphalen** [comment]
windows 10 also doesn't seem to work

**Comment by nicam** [comment]
Same issue here

**Comment by nicam** [comment]
@normen I found a workaround:

You need to copy the necessary files into the path-to-executable dir, in my base bin/

```
cp node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/Resources/en.lproj/MainMenu.nib bin/notifier
cp node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/Info.plist bin/notifier
cp node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier bin/notifier
```

Then you need to create your own notifier, using customPath:

`const notifier = new NotificationCenter({
  customPath: path.resolve() + '/notifier/terminal-notifier',
});`

**Comment by GerkinDev** [comment]
For Windows 10 users, *pkg* is actually misconfigured. I've just sent a PR to fix this: https://github.com/vercel/pkg/pull/1021.

**Comment by SrBrahma** [comment]
@GerkinDev  i still have the 

<details><summary>errors</summary>

```

> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/node-notifier/vendor/notifu/notifu.exe
  %2: path-to-executable/notifier/notifu.exe
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/node-notifier/vendor/notifu/notifu64.exe
  %2: path-to-executable/notifier/notifu64.exe
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS/terminal-notifier
  %2: path-to-executable/notifier/terminal-notifier
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/node-notifier/vendor/snoreToast/snoretoast-x64.exe
  %2: path-to-executable/notifier/snoretoast-x64.exe
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/node-notifier/vendor/snoreToast/snoretoast-x86.exe
  %2: path-to-executable/notifier/snoretoast-x86.exe
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/node-notifier/vendor/notifu/notifu.exe
  %2: path-to-executable/notifier/notifu.exe
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/node-notifier/vendor/notifu/notifu64.exe
  %2: path-to-executable/notifier/notifu64.exe
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS/terminal-notifier
  %2: path-to-executable/notifier/terminal-notifier
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/node-notifier/vendor/snoreToast/snoretoast-x64.exe
  %2: path-to-executable/notifier/snoretoast-x64.exe
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/node-notifier/vendor/snoreToast/snoretoast-x86.exe
  %2: path-to-executable/notifier/snoretoast-x86.exe
  ```

  </details>

**Comment by Asteroid77** [comment]
> @GerkinDev i still have the
> 
> errors
> Do someone know how to get it working for windows at least?

Hello, i resolve it finally.
Maybe will helpful for you:)

first i use `pkg -t win package.json -d` to open the debug mode to find what's up
it show me that:
```
(function (exports, require, module, __filename, __dirname) { import notifier from 'node-notifier';
                                                              ^^^^^^
SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:89:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
> Warning Failed to make bytecode node12-x64 for file C:\snapshot\test\test.js
```
The problem is about ES6 module,i try to use babel complie my entry:
```
babel test.js -d dist --presets es2015 --copy-files
```
and use pkg to handle the compiled file :
```
pkg -t win "compliedFile" -d
```
it works fine
> copy the notifu.exe , notifu64.exe , snoretoast-x86.exe , snoretoast-x64.exe  , terminal-notifier to `path-to-executable/notifier/`

**Comment by Mike-Van** [comment]
> @normen I found a workaround:
> 
> You need to copy the necessary files into the path-to-executable dir, in my base `bin/`
> 
> ```
> cp node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/Resources/en.lproj/MainMenu.nib bin/notifier
> cp node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/Info.plist bin/notifier
> cp node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier bin/notifier
> ```
> 
> Then you need to create your own notifier, using customPath:
> 
> `const notifier = new NotificationCenter({ customPath: path.resolve() + '/notifier/terminal-notifier', });`

this answers also works for me

**Comment by kulek1** [comment]
> @normen I found a workaround:
> 
> You need to copy the necessary files into the path-to-executable dir, in my base `bin/`
> 
> ```
> cp node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/Resources/en.lproj/MainMenu.nib bin/notifier
> cp node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/Info.plist bin/notifier
> cp node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier bin/notifier
> ```
> 
> Then you need to create your own notifier, using customPath:
> 
> `const notifier = new NotificationCenter({ customPath: path.resolve() + '/notifier/terminal-notifier', });`

Thanks. It works but with small caveats in my case:
1.  `bin/notifier` **needs to be a directory** so `cp` command should have `/` at the end of `bin/notifier` like this:

```bash
cp node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/Info.plist bin/notifier/
cp node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier bin/notifier/
```
2. I have my production build in `bin` directory so `path.resolve()` wasn't resolving a proper path because it was pointing to `$HOME`. To fix that, I used `process.execPath` like this:
```js
{
  customPath: path.join(
    process.execPath,
    '../',
    'notifier/terminal-notifier',
  ),
}
```
I spent some time trying to figure out why it doesn't work for me so I hope I'll save you guys a few hours of debugging.

**Comment by jmw11x** [comment]
Same error none of the above solutions are working.

File structure

Notify
   bin/notifier
   node_modules
   index.js
   package.json
   package.lock.json
   .pem file





![Screen Shot 2023-06-06 at 4 36 34 PM](https://github.com/mikaelbr/node-notifier/assets/58860356/7acd893e-f3fd-4b4e-9454-b772d87b5221)

**Comment by jmw11x** [comment]
None of the above solutions are working anymore. See my below file structure. Where am I going wrong? pgk . does not work either.

![Screen Shot 2023-06-06 at 5 03 58 PM](https://github.com/mikaelbr/node-notifier/assets/58860356/a1274e99-3e81-40fc-9fb7-00cf06accb03)
![Screen Shot 2023-06-06 at 5 04 09 PM](https://github.com/mikaelbr/node-notifier/assets/58860356/39f93d1a-bf5e-4704-a5b2-710da5bcb4dd)

**Comment by amirrezaDev1378** [comment]
Here is what worked for me on Windows:
1. Added a simple command to my Windows build: `copy ./node_modules/node-notifier/vendor/snoreToast/** ./notifier`
2. Created a global Windows toast instance and used it across my app:
```ts
import notifier from "node-notifier";

export const AppNotifier = new notifier.WindowsToaster({
    withFallback: true,
    customPath: path.resolve(process.cwd() , "./notifier/snoretoast-x64.exe"),
})
```

It's working properly with both the PKG build and local development.
