### ISSUE TITLE
Update notifu to 1.6.1

### ISSUE THREAD

**Issue by No0Vad** [mikaelbr/node-notifier#222]
Using the WindowsBalloon on Windows 10 with all the updates, display a extra message in the ballon from Notifu.
1.6.1 of Notifu fixes it.
(https://www.paralint.com/projects/notifu/changelog.html)

Current, 1.6
![Current, 1.6](https://i.imgur.com/r1KOgEd.jpg)

With Latest 1.6.1
![Latest 1.6.1](https://i.imgur.com/AFDCkJK.jpg)

**Comment by varyen** [comment]
Confirming this

**Comment by No0Vad** [comment]
It works :)
![asd](https://user-images.githubusercontent.com/9308455/42346201-26e12df4-80a2-11e8-8661-9fb58eec2fcb.jpg)

**Comment by No0Vad** [comment]
When will the NPM package be updated?
https://www.npmjs.com/package/node-notifier

**Comment by mikaelbr** [comment]
Sorry.

It has been done now

```
+ node-notifier@5.3.0
```

**Comment by No0Vad** [comment]
Thank you!
