### ISSUE TITLE
Feature: Emoji instead of icon

### ISSUE THREAD

**Issue by ugrupp** [mikaelbr/node-notifier#231]
Title says it, how about allowing emojis in addition to icons? It would save the extra image file in the repo and also because why not!

Of course, icons and emojis would be mutually exclusive.

**Comment by mikaelbr** [comment]
Hi! Thanks for the issue. I'm afraid this isn't something node-notifier can solve, as it has to be supported by the underlying dependencies (terminal-notifier, growl, notify-send and snoarToast). And even for them I don't think it's possible as e.g. Notification Center API in built in macOS doesn't support it AFAIK.

**Comment by ugrupp** [comment]
Ah bummer. Alright, thanks for the fast reply anyway!
