### ISSUE TITLE
Notifier.notify() should get called when API route is hit

### ISSUE THREAD

**Issue by NicolasPerl** [mikaelbr/node-notifier#235]
Context: 
I have built an online collaboration tool. I would like a desktop notification to appear to the other users when a message is sent. I have placed the code below in my API call for posting a new message (as a test). I am testing with ubuntu.  
` notifier.notify({
        'title': 'My notification',
        'message' : 'Hey, its nick'
    });`

When hitting the API route that would fire the notifier.notify() method nothing happens. I get no errors either so I'm not quite sure the issue. Also, I was under the impression I would have to ask the users for permission to send desktop notifications, but I don't see anything regarding permissions.

Any advice/ guidance is greatly appreciated. Thanks so much!

My macOS is 10.13.

**Comment by mikaelbr** [comment]
Hi, @NicolasPerl ! This package is intended for desktop-apps/server-apps (like CLI tools, Electron apps, etc) and does not run in the browser. There is a built in standard API in the browser to do that, though 👌 Check out some examples and the docs on: https://developer.mozilla.org/en-US/docs/Web/API/notification
