### ISSUE TITLE
node-notifier and webpack.

### ISSUE THREAD

**Issue by redplane** [mikaelbr/node-notifier#242]
Hi,

I'm using `node-notifier` to display notification on windows.
For electron app without web-pack, it works fine.
When I started using `webpack` to bundle my app, the notification isn't shown anymore.

Am I missing anything ?

**Comment by mikaelbr** [comment]
Hi!

Have you tried this https://github.com/mikaelbr/node-notifier/blob/48b0c38907aa8a398db8df14c50c7b10d4e0c619/README.md#using-webpack?

**Comment by redplane** [comment]
Hi,

I've found this [topic](https://github.com/mikaelbr/node-notifier/issues/94).
Intended to remote this question :)

Thanks for your quick support.
