### ISSUE TITLE
How to set focus back to app when clicked on notification.

### ISSUE THREAD

**Issue by sarfarazansari** [mikaelbr/node-notifier#249]
Hello,

here are the library versions
`"node-notifier": "^5.2.1"`
`"electron": "1.8.4",`

am using this plugin in `electron-angular` project and in all cases it is working fine for me.

but am not able to set focus back to my app when clicked on notification.
also am not able to remove the terminal icon from title in mac.

![image](https://user-images.githubusercontent.com/3416989/43642629-fa589910-9745-11e8-8cc8-02196cfe9e6d.png)

**Comment by sarfarazansari** [comment]
I found the solution sorry for inconvenience caused

**Comment by kevinelliott** [comment]
@sarfarazansari Can you share your solution to make this Issue more useful to others when they search and find this?

**Comment by sarfarazansari** [comment]
@kevinelliott 

here you go [https://gist.github.com/sarfarazansari/069b2d5852739e3d0b17305bddca2b2c](https://gist.github.com/sarfarazansari/069b2d5852739e3d0b17305bddca2b2c)
