### ISSUE TITLE
Click trigger not working on ubuntu 18.04

### ISSUE THREAD

**Issue by Matew92** [mikaelbr/node-notifier#253]
Hi,

I'm trying to trigger the click event on the notification in the render file of an electron application.
When the notification appear and i click on it, nothing happen.

Here below my code.

```
notifier.notify({
            title: "Test",
            message: 'to do personal task!',
            icon: '/electron/images/logo.png',
            wait: true
        });

notifier.on('click', function (obj, options) {
            console.log("click")
        });
```

**Comment by Matew92** [comment]
Hi,

Any update?
according to this [https://github.com/mikaelbr/node-notifier/issues/144#issuecomment-319324058](https://github.com/mikaelbr/node-notifier/issues/144#issuecomment-319324058) I installed the application and I added `appName` on the notify function:

```
notifier.notify({
            appName: 'com.app.id',
            title: "Test",
            message: 'to do personal task!',
            wait: true
  });

notifier.on('click', function (obj, options) {
            console.log("click")
        });
```
But still i didn't manage to get it work ! Any suggestion?
this is my main.js:

```
"devDependencies": {
    "electron": "^2.0.0",
  },
  "dependencies": {
    "electron-store": "^2.0.0",
    "node-notifier": "git+https://github.com/mikaelbr/node-notifier.git",
    "path": "^0.12.7",
    "update-notifier": "^2.5.0"
  }
```

**Comment by mikaelbr** [comment]
Hi! I'm afraid notify-send (as implemented) doesn't support on click actions. See supported options on Ubuntu: https://github.com/mikaelbr/node-notifier#usage-notifysend
