### ISSUE TITLE
Icon never shows

### ISSUE THREAD

**Issue by ToJen** [mikaelbr/node-notifier#254]
Hi, I have tried different ways to display my icon but it doesn't work. Is there a specific extension type required or file size for this to work?

```javascript
        notifier.notify({
            title: 'Test',
            message: `🚀 Success!`,
            icon: path.join(__dirname, '/../assets/Logo.png')
        })
```

and 

```javascript
        notifier.notify({
            title: 'Test',
            message: `🚀 Success!`,
            icon: 'https://my.url.to/Logo.png'
        })
```

**Comment by ToJen** [comment]
I'm on Ubuntu 16.04. 
I checked the link you sent, is `appIcon` actually defined? I'm using the [TypeScript version](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-notifier/index.d.ts).

**Comment by JuanDavidLopez95** [comment]
I second this. I cannot get a custom icon to display when using node-notifier in my ElectronJS project.

**Comment by mikaelbr** [comment]
There might be some things you have to do to resolve pathing on electron. But the more "personal" way (to avoid a small terminal icon in addition to your custom icon) to do this is to do something similar to this: https://github.com/mikaelbr/node-notifier#macos-custom-icon-without-terminal-icon

This is due to how notifications are implemented in macOS

**Comment by mikaelbr** [comment]
@ToJen `appIcon` is the same as `icon` but older API for the underlaying terminal-notifier vendor. It's patched/mapped in the code. I've updated the example to use `icon` now. Question still stands, does the advanced example work for you? If you clone the repo, do `npm install` in the root and `npm run example:mac`, does the icon show?

**Comment by JuanDavidLopez95** [comment]
It works for me now. Just make sure to get the correct path, or else the icon will default to SnoreToast!

**Comment by JuanDavidLopez95** [comment]
> 
> 
> @JuanDavidLopez95 how do you setup the icon path? I'm still getting the zzz icon on my app installer, works on development though.
> 
> This is what I use: `icon: path.join(__dirname, '../assets/img/app-icon.png')`

Monchoz,

The paths used in production vs. development are different. I got my production paths working by experimenting A LOT. For example, I've noticed that some paths in production are relative to where your final .exe is located. 

For example, I have a conditional set for my electron main window to configure its path, depending on whether I am in development or production:
```

isDev ? (process.env.ELECTRON_START_URL || "http://localhost:3000") : url.format({
        pathname: path.join(__dirname, "./../build/index.html")
```

**Comment by monchoz** [comment]
I thought so...thanks!
