### ISSUE TITLE
node-notifier-5.3.0: source code of .exe in directory "vendor"

### ISSUE THREAD

**Issue by luisapace** [mikaelbr/node-notifier#259]
Hi, my team would like to use the package node-notifier-5.3.0 and to approve that I've to verify all its licenses (included those of all of the modules included), and to do that I've to analyze its source code.

Now I've noted that there is a directory "vendor" that includes some binaries (that I assume are coming from entities external to node-notifier code). 

I have to know where are the download location of the source code of those binaries to analyze them and discover their licenses.
 
Could you please help me ?

Thanks a lot.

**Comment by mikaelbr** [comment]
Hi @luisapace .

The binary sources are available through the links at the bottom of the README: https://github.com/mikaelbr/node-notifier#thanks-to-oss

Also I've added License for which I could find in the vendor directory https://github.com/mikaelbr/node-notifier/tree/master/vendor

Note: http://www.paralint.com/projects/notifu/ doesn't have an explicit license, other than "free, open source"

**Comment by luisapace** [comment]
Great, thanks a lot Mikael!

I've been able to found the versions of those dependencies for 
node-notifier-5.3.0:

notifu: 1.6.1
terminal-notifier:      1.7.2

but I cannot find it for snoreToast: do you know what version of 
snoreToast in included in node-notifier-5.3.0?

Thanks again for your collaboration.

Best Regards/Cordiali saluti
                                           Luisa Pace


Ing.  Luisa Pace
IBM Italy
IBM Cloud Legal Project Manager 
Via Sciangai, 53  (B1 - 508)
00144 Roma
Italy
Tel. +39.06.5966.3795
Fax. +39.06.5966.3489
mob. +39.335.7368629
e-mail:  luisa_pace@it.ibm.com

**Comment by mikaelbr** [comment]
It is the current version availeble at https://github.com/KDE/snoretoast. In other words: SnoreToast 0.5.1

**Comment by luisapace** [comment]
Thanks a lot!!!!!!

**Comment by mikaelbr** [comment]
No worries. Have a great weekend, @luisapace

**Comment by luisapace** [comment]
thanks, you too!
