### ISSUE TITLE
No more notification alerts on Windows 10

### ISSUE THREAD

**Issue by electrotype** [mikaelbr/node-notifier#266]
I'm not sure if this is something you or I can fix, or if it is an option now disabled by Windows.

We use _node-notifier_ to display notifications. Since of a couple of days (weeks?), there are no more alerts popping on Windows 10... The notifications are only visible by clicking the notifications icon in the traybar.

I checked the settings for "SnoreToast" notifications and "Show notification banners" is on.

Any idea?

**Comment by mikaelbr** [comment]
Hm. Interesting. What version of WIndows 10 are you running? Have you tried using snoretoast directly and see similar issues?

**Comment by electrotype** [comment]
WIndows 10 Pro
Version 1809

I tried with snoretoast directly and it didn't work either.

But, following this article, I was able to make the alerts appear again!

https://www.technorms.com/41496/enable-balloon-toasts-notifications-in-windows-10
