### ISSUE TITLE
node-notifier not working on the remote

### ISSUE THREAD

**Issue by nandy2013** [mikaelbr/node-notifier#276]
I have created very small api to upload the file to the local system. Upon completion, i want to trigger the notification saying the upload is completed. This is working fine when I access through the local URL - localhost:3000. 

But the notification not coming while trying to access on the different system using my system IP address: sample URL - http://10.200.90.200:3000/.

Any help would be appreciated!

**Comment by nandy2013** [comment]
Any help on this please!

**Comment by mikaelbr** [comment]
Hi, do you have any code so we can see? This isn’t related to node-notifier, strictly speaking. Node-notifier is just a local tool for communicating with your OS, and doesn’t care if you have a http api built on top of it.

**Comment by nandy2013** [comment]
My app.js code:

const express = require("express");
const app = express();
const http = require("http").Server(app).listen(3000);

const notifier = require("node-notifier");

console.log("Server Started");
app.get("/", function (req, res) {
  res.send("Loaded");
  notifier.notify("test");
})

I am receiving the notification while run on the local. When I tried to access on another machine using my machine ip address, the notification is still sending to my local machine.

**Comment by mikaelbr** [comment]
Yes. Sorry, but this is expected behaviour. There is no built in support for notifications a cross networks in node-notifier. It's only a tool for communicating with the OS of the computer running node-notifier.
