### ISSUE TITLE
Closing notifications

### ISSUE THREAD

**Issue by adam-lynch** [mikaelbr/node-notifier#28]
It would be nice if the API supported a way of triggering the closing/hiding of a notification.

I'd be using just the Windows 8 ones and being able to close them all when one is clicked would be nice. With other libraries, I keep track of the open notifications, loop over them and close them one by one.

**Comment by mikaelbr** [comment]
I'm afraid this isn't feasible considering the cross platform support.

**Comment by adam-lynch** [comment]
Ok, thanks
