### ISSUE TITLE
'click' event runs multiple times after multiple notifications

### ISSUE THREAD

**Issue by ItsPaulM** [mikaelbr/node-notifier#282]
I'm aware of the other issue regarding this but it's fairly old.

So it's pretty much the same issue. 

Image of the issue:
![image](https://user-images.githubusercontent.com/23089320/62504568-0deabe00-b7f1-11e9-8608-ec84f60c13a6.png)

I have put the event thing in it's own function.

Here's the code for the notifier stuff -- 'url' is a variable used in other parts of the code so ignore that:

```
function onClickEvent(url) {
    notifier.on('click', function (obj) {
        opn(url);
        log('Clicked!');
    })
}
```

```
notifier.notify({
                title: 'Title',
                message: 'Message',
                icon: './assets/logo.png',
                wait: true,
                onClickEvent: onClickEvent(url)
            })
```

I'm quite new to node so if possible, please keep the response as simple as possible :)

**Comment by major697** [comment]
@ItsPaulM Hi, I have this same problem, Did you fix this ?

**Comment by jnielson94** [comment]
Hi @ItsPaulM - If you did get this figured out, let us know what worked and we can try to update our docs. Otherwise, if your code is available I'd love to pull it down and try and see if I can figure it out.

If your code isn't available, that's fine. If you can share what version of the library you're using and what platform you use (node with the version, electron with the version, that kinda thing)?

**Comment by pjebs** [comment]
OS: MacOS
This issue still exists. I have multiple notifications that have run in the past. Each one has a callback.
Not all notifications were called for past notifications, hence not all callbacks were called.

However, when you do click on a notification, the on click call back seems to be called FOR ALL past notifications too.

**Comment by pjebs** [comment]
My solution was: `notifier.removeAllListeners()` before calling each notification.

**Comment by rosvik** [comment]
In your example, you add a new event listener each time the notification is sent. You can use a callback function instead, that checks `activationType`.

```
notifier.notify(
    {
        title: 'Title',
        message: 'Message',
        icon: './assets/logo.png',
        wait: true,
    }, 
    function(err, res, metadata) {
        if (metadata.activationType == 'contentsClicked') {
            console.log("Clicked!")
        }
    }
)

```
