### ISSUE TITLE
timeout: false is not working in v5.4.3

### ISSUE THREAD

**Issue by weilinzung** [mikaelbr/node-notifier#286]
why keep reverting it back? And When V6 would be published? The other 3-4 months?

**Comment by mikaelbr** [comment]
There's been some memory leaks and issues with the timeout property. See #271. The v6 branch currently contains the new timeout semantics. master branch is currently held clean to easier do patch releases if needed until we get the wanted scope for v6.

**Comment by weilinzung** [comment]
@mikaelbr ok. hopefully quick.
