### ISSUE TITLE
Click event doesn't work

### ISSUE THREAD

**Issue by ihor-zinchenko** [mikaelbr/node-notifier#291]
hH! Windows 10 latest
What did i do wrong?

```js
constructor(serve) {
    this.serve = serve;
    const defaultIconPathPrefix = this.serve ? '/../../src/assets/' : '/../../dist/secure-box/assets/';
    this.defaultIconPath = path.join(__dirname, defaultIconPathPrefix + 'icons/icon-72x72.png');
    notifier.on('click', (notifierObject, options, event) => {
      console.log('click ', 1);
      console.log('obj ', notifierObject);
      console.log('opti ', options);
      console.log('event ', event);
    });
    notifier.on('timeout', (notifierObject, options) => {
      console.log('finish ', 1);
    });
    this.subscribeToShowing();
  }

  public subscribeToShowing() {
    ipcMain.on('notification', (event, data) => {
      // event.returnValue = 'pong';

      notifier.notify({
        message: data.message,
        title: data.title,
        sound: data.sound || true, // "Bottle",
        icon : data.icon || this.defaultIconPath,
        wait: data.wait || true,
      }, (err, res) => {
        if (err) {
          return;
        }
      });
    });
  }
```

When I click on a notification click event doesn't work

**Comment by major697** [comment]
Hi, I have this same error. I'm back to version 5.4.0 and then click event work correctly

**Comment by jnielson94** [comment]
Hi @IhorVimmi and @major697 - Do either of you happen to have a reproduction repo that I could pull down and try it? Last I checked out internal examples were working, but it could be that your setup is causing something to not trigger correctly.

**Comment by fsykes87** [comment]
I am having the same issue with onClick event not firing. has anyone found a fix?

**Comment by IhorVimmi** [comment]
@jnielson94 I start using default Electron notifications, so I fix that issue by another way) unfortunately i haven't my code before the fix.

**Comment by jnielson94** [comment]
@fsykes87 - I've poked around a little bit and it looks like `click` events haven't worked in the windows toaster since v5 of `node-notifier`. I would try for now (since we don't currently have a fixed version published but it's in the works), utilizing the callback, which should be working. Something like:

```
notifier.notify({
 ... options
}, (err, action, metadata) => {
	// utilize err to handle an error firing the notification
	// utilize action as a short key of what happened (activate = clicked, otherwise it'll be `timeout` or something from the native library)
	// utilize metadata for more information. Log it out to see what it contains in your testing 😄 
```

The timeout event should work still, but [this line in the windows toaster](https://github.com/mikaelbr/node-notifier/blob/v5.4.3/notifiers/toaster.js#L63) didn't get updated to account for changes that turn `clicked` -> `activate` in v5 on [this line in a utility function](https://github.com/mikaelbr/node-notifier/blob/v5.4.3/lib/utils.js#L245). 

Ideally with v7 (which is in the works) we'll get the event worked out.

**Comment by Revadike** [comment]
I had the same error with the latest version
going back to 5.4.3 works

**Comment by 1111mp** [comment]
Is there a solution?

**Comment by fsykes87** [comment]
No

**Comment by DinerIsmail** [comment]
This is still not fixed, so we're stuck on 5.4.3 as it's an essential piece of functionality for notifications. Did anyone find a workaround?

**Comment by DinerIsmail** [comment]
@mikaelbr this was closed but the fix hasn't been released yet, any plan to release it soon?

**Comment by fzs1994** [comment]
@mikaelbr Click event is still not working on 9.0.0

**Comment by Revadike** [comment]
Actually, it's working for me on the latest version.
