### ISSUE TITLE
Clarify collaborator role

### ISSUE THREAD

**Issue by jnielson94** [mikaelbr/node-notifier#296]
Hi @mikaelbr! Not sure on the best way to contact you, so I figured I'd throw it out here. I had a few questions as I've been helping that I was hoping you'd be able to fill in some blanks I've had.

1. What role do you want me to fulfill as a collaborator? It looks like I've got write access to the repo, so I've been helping review issues and PRs, but I haven't yet merged anything yet. I wasn't sure if that was something you'd still want to do, or if you wanted me to help with that even though I don't have permissions (so far as I'm aware) to publish to npm.
2. What's the best way to contact you if I have a question like this in the future? The email on your github profile (which I assumed this issue would be sent to)? Or another way?
3. Do you have any sort of roadmap/vision for the project in mind right now? Or is it essentially keeping it in a maintenance mode where we try to stay semi up to date and keep things working for as many people as possible?

Thanks!
Jordan

**Comment by mikaelbr** [comment]
Hi! I’m on the road just now, so just answering quickly. But for me you can take as much ownership as you want, and feel like. I hope you want to share with me. Merge if you want, commit what you want. Tell me if you want to publish a new release and I’ll look over it and publish on npm.

You can contact me where ever. Like mikaelbre@gmail.com or @mikaelbrevik on Twitter.

Roadmap is pretty much keep it stable, expand what is natural to maintain a consistant api (like the new toaster reply stuff) but avoid too much feature creep, if that makes any sense? I’m would also like a modern rewrite, but favoring stability most of all.

Hope this helps. Hit me up if you want to talk more.

**Comment by jnielson94** [comment]
Sounds good! I'm definitely wanting to share with you - and have no intention of taking over completely 😆 I'll probably use email for contacting if I don't want it in the open on github (aka if it isn't related to a PR/issue, for those I'll just mention you like I've been doing). 

Roadmap sounds good for now. I'll probably spend some time thinking of clearer way to describe the project to avoid feature creep and enable us to look towards a more modern rewrite (since the current description makes it sound like we'll forever support everything 😆 ).

Thanks for getting back to me so quickly! Hope your travels go well.
