### ISSUE TITLE
Permission denied when call snoretoast-x64.exe under wsl

### ISSUE THREAD

**Issue by Gerhut** [mikaelbr/node-notifier#298]
Platform: Windows (WSL)

It works after `chmod +x` to the exe files in node_modules/node-notifier/vendor/snoreToast

**Comment by jnielson94** [comment]
Hi @Gerhut - Which version of node-notifier did you run into this on? :)

**Comment by Gerhut** [comment]
Hi @jnielson94 I installed `node-notifier 6.0.0` by yarn

**Comment by jakedowns** [comment]
ah, i opened (and closed) a dupe issue on this https://github.com/mikaelbr/node-notifier/issues/353

**Comment by jakedowns** [comment]
@mikaelbr can probably close this issue now that you have the Readme note added
https://github.com/mikaelbr/node-notifier/commit/2ce63545f119c89e94924f9de5affa222c4b5d52

:)
