### ISSUE TITLE
electron-notification-state library

### ISSUE THREAD

**Issue by pjebs** [mikaelbr/node-notifier#302]
It would be nice if this package could integrate the features from here: https://github.com/felixrieseberg/electron-notification-state

This repo is now deprecated and not even working.

**Comment by mikaelbr** [comment]
Hi. Thanks for the comment. This module is general purpose and not specifically for Electron. I would suggest for users to use it consumer side, but not something we should have as a part of this.

**Comment by pjebs** [comment]
The package is not specific to electron although it says so.
