### ISSUE TITLE
Mac notification doesn't show

### ISSUE THREAD

**Issue by gabrielmoncea** [mikaelbr/node-notifier#308]
Hello,

I'm using:
macOS Catalina 10.15.2
node v10.16.3
node-notifier v6.0.0

I tried the quick start and is not working

**Comment by jnielson94** [comment]
Hi @gabrielmoncea! Could you explain more of what isn't working? When I create a small sample project it looks to work just fine on my computer: https://github.com/jnielson94/node-notifier-simple

Does that sample work for you? If not, can you share more of what isn't working? :)

**Comment by gabrielmoncea** [comment]
@jnielson94 it's working now. I'm not sure why it wasn't.
Sometimes a restart of the mac and a good night sleep for the brain solves things 👍

**Comment by lnfel** [comment]
I am in the same limbo right now, I guess I should sleep then. 🤣 

Alright I got the solution. Need to turn on terminal notifier in MacOS first.
```
System Preferences > Notifications > Terminal Notifier
```
Turn on and Select Alerts to persist notifier
