### ISSUE TITLE
node-notifier-6.0.0: level of binaries included

### ISSUE THREAD

**Issue by luisapace** [mikaelbr/node-notifier#316]
Hi, my team would like to use the package node-notifier-6.0.0 and to approve that I've to verify all its licenses (included those of all of the modules included), and to do that I've to analyze its source code.

So, I need to know what is the version of the opensources that have been included in node-notifier-6.0.0:

    terminal-notifier
    Snoretoast
    notifu
    growly

Could you please help me ?

Many thanks.

**Comment by luisapace** [comment]
Hi, are there any news on this?

**Comment by mikaelbr** [comment]
This is specified here https://github.com/mikaelbr/node-notifier#thanks-to-oss and licenses are included here https://github.com/mikaelbr/node-notifier/tree/master/vendor

**Comment by luisapace** [comment]
Hi, at that link the versions are not showed, anyway I've found myself the info. Thanks.
