### ISSUE TITLE
notifier.on click event is not fired in Windows Action Center

### ISSUE THREAD

**Issue by YuJingGuo** [mikaelbr/node-notifier#325]
I am using the node-notifier package for notification but I have one problem. notifier.on click event is not fired in Windows Action Center
`notifier.notify(
      {
        appId: "com.electron.demo", // Absolute path (doesn't work on balloons),
        title: "Alert Message",
        message: "Click to view",
        icon: path.join(__dirname, 'msicon.png'),
        wait: true,
        timeout: false,
        id: "demo app"
      },
      function(err, response) {
        // Response is response from notification
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      }
    );
notifier.on("click",  function(notifierObject, options, event) {

      // Triggers if `wait: true` and user clicks notification
      var request = new sql.Request();
      let username = userName;
          request.query("update alerts.dbo.groupmessages set isRead = 1\
                            where pk = '"+ recordset.recordset[i].pk + "'\
                            and userFK = (select pk from alerts.dbo.users where username = '"+ username + "')\
                            and groupFK = (select groupFK from alerts.dbo.users where username = '"+ username + "')", function (err, recordset) {
            if (err) throw err
            console.log(err, recordset, 'User shit');
          });          

          function createWindow() {
            // Create the browser window.
            win = new BrowserWindow({
              width: 400,
              height: 400,
              frame: false,
              webPreferences: {
                nodeIntegration: true
              }
            });
            // and load the index.html of the app.
            ejse.data('message', recordset.recordset[i].message);
            win.loadFile('index.ejs')
          }
          createWindow();

        });
    });
  });`

notifier.on click event is not fired in only Windows Action Center. please let me know the reason and solution as well. Thanks.

**Comment by fzs1994** [comment]
@YuJingGuo did you got any solution. I still have same issue with v8.0.0. Click event is neither trigged from directly clicking, nor from the Action Center
