### ISSUE TITLE
node-notifier within node-webkit 

### ISSUE THREAD

**Issue by JacopoDaeli** [mikaelbr/node-notifier#33]
Hi I am trying to use node-notifier within node-webkit and it doesn't work.
When I test the app with nodewebkit module it works perfecty, therefore when I pack my app it doesn't work anymore and I get this from my WebKit Console:
`Command failed: /bin/sh: /Users/jacopodaeli/Desktop/PublipingTrainer.app/Contents/Resources/app.nw/node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS/terminal-notifier: Permission denied`

My App is based on Node-WebKit 0.8.6 and it runs over Mac OS X 10.9.

Anyone can help me with this problem?

**Comment by chukkynze** [comment]
Just in case this may help anyone else, the solution to this kind of problem is basically to adjust your file permissions. Most likely, the file `/Users/jacopodaeli/Desktop/PublipingTrainer.app/Contents/Resources/app.nw/node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS/terminal-notifier` is not executable by the user/runner of the script. What you can do is to cd to the directory `/Users/jacopodaeli/Desktop/PublipingTrainer.app/Contents/Resources/app.nw/node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS/` and check ls -l for the permissions of terminal-notifier. Most likely, you'll be missing an x in the 4th position, in other words, you don't have executable permissions for this file. run `sudo chmod o+x terminal-notifier` to give the owner executable permissions. This should solve this problem

**Comment by mikaelbr** [comment]
Very good! Thanks for clearing that up.

**Comment by doronsever** [comment]
I'm trying to work with it my self.
When i set my customPath to terminal-notifier.app i get this error:

> vendor-48a50c1e.js:25881 Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:387:9)
    at Object.exports.execFile (child_process.js:148:15)

I tried to chmod the file, and even copying the original terminal-notifier.app which comes with node-notifier(which works fine with out customPath)

Any ideas?

**Comment by kurisubrooks** [comment]
`EACCES` refers to a file being unable to be run, executed or found.

When you try to set `customPath`, are you proving `terminal-notifier.app`,
or are you giving it `terminal-notifier.app/Contents/MacOS/terminal-notifier`?
(The 2nd one is the correct one)

**Comment by doronsever** [comment]
10x @kurisubrooks, you were right...
I haven't seen something pointing at this in the docs but i will relook... 10x!
Now i have a different problem, the 'click' event stopped working. Am i missing something again?

**Comment by kurisubrooks** [comment]
Didn't realise this wasn't in the docs, i'll add it soon.
I'll respond to your second question in the appropriate issue.

**Comment by doronsever** [comment]
Thank you very much!

**Comment by kurisubrooks** [comment]
Added to the docs in 346763c

**Comment by mikaelbr** [comment]
Good 👍 It can also be an absolute path, maybe that should be specified also.

**Comment by kurisubrooks** [comment]
I'll update it now.
