### ISSUE TITLE
Hang on Disabled Windows Notifications

### ISSUE THREAD

**Issue by JasonGore** [mikaelbr/node-notifier#334]
## Expected Behavior

Disabling Windows 10 notifications should not hang `node-notifier`.

## Actual Behavior

Running `node-notifier` on Windows 10 clients with notifications results in a hang.

## Repro

The simplest repro is to disable Windows 10 notifications as shown below and run `npm run example` in the repo.

I'm trying a scenario like:

```js
try {
  const notifier = require('node-notifier');
  notifier.notify({
    title: 'Title',
    message: 'message',
    wait: true
  });
} catch {
  // Notifications may be disabled in OS, causing an error.
  // node-notifier may not installed.
  // Silently fail.
}
```

I'd just simply like to catch exceptions and silently continue.

However, if notifications are disabled on Windows 10:

![image](https://user-images.githubusercontent.com/26070760/84810865-cca26d80-afc0-11ea-909c-b0f4b5e25439.png)

This example will hang forever on the command line:

```
λ node not.js
Notifications are disabled
Reason: DisabledForUser Please make sure that the app id is set correctly.
Command Line: G:\git\ooui-dp\node_modules\node-notifier\vendor\snoreToast\snoretoast-x64.exe -pipeName \\.\pipe\notifierPipe-f80dfe8f-ff7d-42ce-becd-0a2e340a9d59 -m message -t Title
```

I tried searching the docs and existing issues for a way to "detect" whether notifications are disabled, but I haven't found anything. I'd also like to suppress error output like this if possible. In any case, it doesn't seem like the call to `node-notifier` should hang like this.

## Tools
node-notifier: 7.0.1
node: 12.18.0
OS: Windows 10 Pro 1909

**Comment by peppelongo96** [comment]
You can't catch any exception due to the right execution of node-notifier. Seems the developer have choosen to print an "error" message about disabled notifications system . Also, for sure, I'm right with you that is an useless info.

**Comment by JasonGore** [comment]
I've done a little more investigation. It appears in this case snoretoast never writes to `pipeName` arg, which means the [named pipe never has a `data` event](https://github.com/mikaelbr/node-notifier/blob/303f024973d74b4e3e4eae59921c5aff23d31863/lib/utils.js#L547) and therefore never has [`end` called](https://github.com/mikaelbr/node-notifier/blob/303f024973d74b4e3e4eae59921c5aff23d31863/lib/utils.js#L550). This means the named pipe server keeps running which is what's causing the hang.

I have a local fix that passes back the server instance to `toaster.js` so that it can make sure the server is closed. I'm not sure if it's the best fix but I can make a PR.

**Comment by JasonGore** [comment]
Some more findings: The error output is generated [in snoretoast](https://github.com/KDE/snoretoast/blob/d424758e83ad319c058edb74541e247a6de8e4fc/src/snoretoasts.cpp#L566) but bypasses standard stdio constructs entirely. It doesn't even come through on `stdio` via Node. It appears the reason is due to [snoretoast's use of AttachConsole](https://github.com/KDE/snoretoast/blob/master/src/main.cpp#L314), which prevents this error output from feeding back into node-notifier.

**Comment by JasonGore** [comment]
I've entered a [snoretoast bug](https://bugs.kde.org/show_bug.cgi?id=423076) as well.

**Comment by JasonGore** [comment]
I have a PR that doesn't totally fix the issue (due to snoretoast's behavior) but at least resolves the hanging issue. I think it's important to fix with some kind of change at least temporarily to prevent a permanent hang in certain use cases.
