### ISSUE TITLE
growly dosent support network notifications

### ISSUE THREAD

**Issue by moxx** [mikaelbr/node-notifier#34]
Hi,

growly has no option to overwrite the hostname (localhost in gntp) for push growl notifications over network (useful for vm develop env).
Maybe use [Growler](https://github.com/betamos/Node-Growler) instead.

**Comment by moxx** [comment]
should be implemented in growly ->
https://github.com/theabraham/growly/commit/547bf6963a96686dc433a9a523f7721aea3f79fa

**Comment by mikaelbr** [comment]
Very good! Thanks
