### ISSUE TITLE
How actions supports Chinese

### ISSUE THREAD

**Issue by 1111mp** [mikaelbr/node-notifier#340]
```
notifier.removeAllListeners();
      notifier.notify(
        {
          message: 'Hello',
          wait: true,
          timeout: false,
          actions: ['确认', '取消'],
        },
        function (err, data) {
          // Will also wait until notification is closed.
          console.log('Waited');
          console.log('确认');
          console.log(err, data);
          // if(`${data}`.toString('utf8le') == '确认') {
          //   console.log('866666633333333')
          // }
        }
      );
      notifier.on('activate', () => {
        console.log('Clicked!');
      });
      notifier.on('dismissed', () => {
        console.log('Dismissed!');
      });
      // Buttons actions (lower-case):
      notifier.on('确认', () => {
        console.log('"Ok" was pressed');
      });
      notifier.on('取消', () => {
        console.log('"Cancel" was pressed');
      });
```
If I use Chinese, the corresponding event will not be executed.
It should be that the activation type has changed after the buff is converted. How to solve this problem. Please help me. thank you.
![image](https://user-images.githubusercontent.com/31227919/89491128-1ea58980-d7e1-11ea-8f0c-6f12c907402b.png)

**Comment by mikaelbr** [comment]
I belive this might be an issue with terminal-notifier, the underlying implementation for Notification Center in MacOS

**Comment by 1111mp** [comment]
I'll go to terminal-notifier to find out. Thank you very much.

**Comment by 1111mp** [comment]
> I belive this might be an issue with terminal-notifier, the underlying implementation (dependency of this project) for Notification Center in MacOS

I have the problem on Windows 10. Sorry,I didn't make it clear.
It might be an issue with snoretoast.
Thanks again.
