### ISSUE TITLE
Chinese Support?

### ISSUE THREAD

**Issue by JasonkayZK** [mikaelbr/node-notifier#344]
How to support chinese nitification?
I found it wrong when i write someting like this:
```javascript
    notifier.notify(
        {
            title: '大家好',
            message: '放假休息重要通知',
            icon: path.join(__dirname, 'clock.ico'),
            sound: true,
        },
    );
```
And the result it pretty ugly like this:
![1602646752(1)](https://user-images.githubusercontent.com/40811521/95940875-028e1c00-0e12-11eb-9839-caad1c128c67.jpg)

So i was wondering how can i change the encoding when send notifications. Thanks!

**Comment by mikaelbr** [comment]
Hi! This looks like an issue with the encoding snoretoast itself. Does it work if you use it directly manually through the command line?

**Comment by JasonkayZK** [comment]
It's weird! Somehow it works with pure snoretoast-cli!
![1603417592](https://user-images.githubusercontent.com/40811521/96947132-e4f93a80-1514-11eb-9056-9e6c44bbbfbd.jpg)

**Comment by felixhao28** [comment]
Chinese displays fine on my computer. Maybe you can try saving the js source file in UTF-8 encoding?

**Comment by JasonkayZK** [comment]
It's weird, because the js file is already in UTF-8 encoding!

**Comment by a958330481** [comment]
Does actions support Chinese? like this:

`     notifier.notify(
                {
                    title: "任务结束",
                    message: "是否开始休息?",
                    sound: true,
                    actions: ["确认", "取消"],
                },
                (error, response, metadata) => {
                    console.log(response, metadata);
                }
            );`
