### ISSUE TITLE
Custom contentImage doesnt load

### ISSUE THREAD

**Issue by SentoxAIO** [mikaelbr/node-notifier#350]
I am using `node-notifier` on an Electron app made with Typescript and React.

When I try to use a custom image as a contentImage, it only loads the default SnoreToast one:

![Screenshot 2020-11-14 172619](https://user-images.githubusercontent.com/57367608/99151898-9156b880-269e-11eb-9efd-82d01ad91e0b.jpg)

```
	notifier.notify({
		title: "<TITLE>",
		message: `<MESSAGE>`,
		contentImage: path.join(__dirname, "../assets/logo.png"),
		appName: `<APP NAME>`,
	});
```

**Comment by jakedowns** [comment]
guessing it's cause you needed to use the .icon property, not the webpack-notifier "contentImage" one, yeah?
