### ISSUE TITLE
WSL2: had to manually chmod +x on snoreToast/snoretoast-x*.exe

### ISSUE THREAD

**Issue by jakedowns** [mikaelbr/node-notifier#353]
just fyi, this tripped me up for a while, and in case anyone on google stumbles on this, if you try running, say:
`DEBUG=notifier npm run mix` or whatever (in my case i'm looking for laravel-mix / webpack-notifier messages)

and you SEE notifier path and notifier options are called, but you never SEE the notifications,
and you checked Notification Settings, and they're enabled for SnoreToast,

you _may_ need to manually add +x permissions to those exe files within WSL2 for them to actually execute.

maybe a note that could be added to the ReadMe wrt WSL, and/or something that could happen auto-magically via a build step? /shrug

thanks for a great tool!

**Comment by jakedowns** [comment]
FWIW, this happened with 6.0.0 and 8.0.0

**Comment by mikaelbr** [comment]
Thanks. Added note in readme!

**Comment by pkkummermo** [comment]
Just had this problem and had to `chmod +x ` the .exe vendor files. As a reference, these are the steps you need to run after installing the package. 

```
chmod +x node_modules/node-notifier/vendor/snoreToast/snoretoast-x64.exe
chmod +x node_modules/node-notifier/vendor/snoreToast/snoretoast-x86.exe
```

Cheers!
