### ISSUE TITLE
Notifier icon and name

### ISSUE THREAD

**Issue by mydigitalself** [mikaelbr/node-notifier#36]
Hi there,

Couple of questions more than anything else as I couldn't find it in the documentation, unless I've missed it somewhere...

As per your example image on the Mac:
[!Example](https://raw.githubusercontent.com/mikaelbr/node-notifier/master/example/mac.png)
1. Why does the terminal icon persist even if you specify appIcon and, more importantly, how can you get rid of it?
2. In notification center, it still shows up with the terminal icon as well as being titled as "terminal-notifier". How can this be changed?

Thanks
Mike

**Comment by sergiovilar** [comment]
`sender` option works fine, thank you.
