### ISSUE TITLE
Cherry-pick security patch into version 5.4.3

### ISSUE THREAD

**Issue by Aleks-gdb** [mikaelbr/node-notifier#363]
Would it be possible to patch version 5.4.3 with this commit?
https://github.com/mikaelbr/node-notifier/commit/b9d148d697d3db807f653e2e6953c3de57dfeb8a

**Comment by Travisshawn6** [comment]
Work hard to get with you.

**Comment by Travisshawn6** [comment]
#187

**Comment by Aleks-gdb** [comment]
Just wanted to follow-up on this

**Comment by mikaelbr** [comment]
This should be fixed now with additional security fixes in `v5.4.5`.
