### ISSUE TITLE
npmjs.com has v8 as "latest", does not distribute v9+ by default

### ISSUE THREAD

**Issue by mikehardy** [mikaelbr/node-notifier#366]
Howdy! Thanks for node-notifier :-)

Just noticed that v9.0.1 is showing up on my outdated dependencies report, but v8 is what comes down by default

Quick check on npmjs.com and it looks like it is because the latest tag has not been applied to the new releases?

https://www.npmjs.com/package/node-notifier (on the Versions tab)

Why? Unsure - must be something about how you publish but I didn't see anything related in package.json

Thought you'd want to know :-)

**Comment by mikaelbr** [comment]
Sorry! My fault when updating different major versions to patch security issues. Updated now. Thanks for letting me know!
