### ISSUE TITLE
Notificacion not showing while we are in games

### ISSUE THREAD

**Issue by f1729** [mikaelbr/node-notifier#367]
Hi, I know this is not directly related with the library but I would like to know if there is someway to show the notificacion doesn't matter what we are doing, like the chrome/youtube notificacions. 

SO: Windows 10
Game: Dota 2

**Comment by mikaelbr** [comment]
Looks to be something with Focus Assists: https://www.howtogeek.com/435349/how-to-disable-windows-10s-annoying-focus-assist-notifications/
