### ISSUE TITLE
Doesn't work on nexe

### ISSUE THREAD

**Issue by lee1409** [mikaelbr/node-notifier#377]
I was trying to compile my node project into .exe using Nexe. I'm clueless because node-notifier does work on node but not .exe. The .exe file doesn't display any error or something that can give me some hints about what kind of problem I encountered. 

**Version**
"node-notifier": "^10.0.0",
"nexe": "3.3.7"

**Comment by yoavain** [comment]
This is the error message I get when updating from 9.0.1 to 10,0,0
```
(node:13544) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `windows-authenticator --trace-deprecation ...` to show where the warning was created)
```
Hope this helps...

**Comment by yoavain** [comment]
I think I found something. It seems to be related to the `customPath` option. (This also fits the release notes that mention a fix there)

My notifierOptions:
```
{
	"withFallback": false,
	"customPath": "X:\\xxxxxxxxxx\\dist\\snoretoast-x64.exe"
}
```
Debug log
```
node-notifier debug info (fileCommand):
[notifier path] X:\xxxxxxxxxx\dist\vendor\snoreToast\snoretoast-x64.exe
```

Seems that somewhere along the way the `vendor\snoreToast` is added.
Not sure if that's only when using an absolute path to the binary, or if it will happen to relative as well.

**Comment by yoavain** [comment]
Although the documentation note `Relative/Absolute path to binary`, even when removing the `sonretoast-x64.exe` from the customPath, the result is the same.
So it seems the actual behavior of `customPath` is that it expects a folder with `vendor\snoreToast\sonretoast-x64.exe` rather then a path to binary itself.

**Comment by yoavain** [comment]
Found the problem. Opened a PR

**Comment by yoavain** [comment]
@lee1409 
If your problem you're having is the same as mine, a temporary workaround can be sending `customPath` in the message options rather then in the WindowsToaster constructor

**Comment by lee1409** [comment]
Alright thanks @yoavain ! Will try it when I'm available
