### ISSUE TITLE
Windows 7 balloon systray oddities

### ISSUE THREAD

**Issue by mydigitalself** [mikaelbr/node-notifier#38]
Hi there, me again!

Couple of questions about Windows 7 behaviour

1. I've noticed when a notification appears in the system tray, there's a little chat-shaped icon that appears in the systray. My app already has a systray icon and indeed the balloon rightfully points to my app's icon. Is there a way to disable to chat icon thing?

2. Clicking on the balloon only appears to dismiss it rather than perform the function in my ```click``` event handler, is this correct?

Thanks
Mike

**Comment by misteroh** [comment]
Sidenote: Is it possible to keep the console notification but disable the Windows balloon notification?

**Comment by mikaelbr** [comment]
@misteroh Are you refering to using gulp-notify here? Node-notifier doesn't have any console notifications, but gulp-notify does. You can disable notification integration (leaving the console messages active) by following [these steps](https://github.com/mikaelbr/gulp-notify#disable-gulp-notify).


@mydigitalself 

> I've noticed when a notification appears in the system tray, there's a little chat-shaped icon that appears in the systray. My app already has a systray icon and indeed the balloon rightfully points to my app's icon. Is there a way to disable to chat icon thing?

I think this is the default balloon behaviour. I'll try to find time to investigate how to do this.

> Clicking on the balloon only appears to dismiss it rather than perform the function in my click event handler, is this correct?

It should trigger the activation "click" event. Maybe a bug?

**Comment by mikaelbr** [comment]
Might #42 help with your second issue?

**Comment by kurisubrooks** [comment]
Hey @mydigitalself, just checking up to see if you got this issue resolved, or if it's still pending.

**Comment by mydigitalself** [comment]
Hey, we ended up switching over to the native io.js notifications, so this isn't affecting us any more. I'll close the issue now, thanks for the follow up.

**Comment by kurisubrooks** [comment]
Alright, thanks to letting us know. Sorry it didn't work out for you.
