### ISSUE TITLE
Command line

### ISSUE THREAD

**Issue by yuvilio** [mikaelbr/node-notifier#40]
Any thoughts about a command line command ? That would replace having to use ```notify-send``` in linux vs ```terminal-notifier``` on mac vs ...

**Comment by mikaelbr** [comment]
That is a really good idea, actually. Just adding a CLI file and a bin-property to the package.json and we'll be good to go. I'll look into it.

**Comment by sholladay** [comment]
+1 for this, would be very useful

**Comment by mikaelbr** [comment]
This is implemented as of `v4.2.0`
