### ISSUE TITLE
node-notifier don't work on macOS 12.2.1

### ISSUE THREAD

**Issue by F3n67u** [mikaelbr/node-notifier#403]
# Reproduce step

```bash
$ cat package.json 
{
  "dependencies": {
    "node-notifier": "^10.0.1"
  }
}

$ cat test.js     
const notifier = require('node-notifier');

notifier.notify({
  title: 'My notification',
  message: 'Hello, there!'
});

# no notification after run test.js, just silently fail
$ DEBUG=notifier node test.js
node-notifier debug info (fileCommandJson):
[notifier path] /Users/feng/test/test-notify/node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier
[notifier options] -title "My notification" -message "Hello, there!" -timeout "10" -json "true"
```

# Expect Behavior

should send a notification 

# Actual Behavior 

no notification shows

# Environment
macOS version: 12.2.1
node: v17.6.0

**Comment by F3n67u** [comment]
I forgot to turn on notification permission to terminal-notifier, so node-notifier won't work. after turn on the permission, notificaton shows.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/12343178/159610217-1b0c6a23-37e0-4ac5-b914-d9259c5503ba.png">

**Comment by Amethystafyy282** [comment]
But how did you manage to ask for permission during production?
