### ISSUE TITLE
Can not listen to the event when set appID

### ISSUE THREAD

**Issue by truongnat** [mikaelbr/node-notifier#408]
On window.

Before starting, set actions for it.

```
notifier.notify({
  title: 'My notification',
  message: 'Hello, there!',
  actions: ["ok","cancel"]
});

notifier.on('ok', function (notifierObject, options, event) {
  // Triggers click ok
});

notifier.on('cancel', function (notifierObject, options, event) {
  // Triggers click cancel
});


```

Case 1: appID = undefined => node-notifier is displayed and listen event work
  - but it is in the snore toast group. not my app.
![image](https://user-images.githubusercontent.com/87919564/168723756-16108b8d-f346-4d2a-acae-7291ac467390.png)

Case 2: appID = my.app.id => node-notifier is displayed and it display is in my app group
 - but listen event not work

**In my case, I want to set appID = my App ID to show my app group and listen to event work.**

_note:_
I have read the source code of node-notifier:

It passes property to SnoreToast.exe and executes it. If set appID for it, Emit Event will not work, I think so.

You can see source here: https://github.com/mikaelbr/node-notifier/blob/master/notifiers/toaster.js

If anyone have solution, plz help me. Thanks all

**Comment by santosh898** [comment]
Hi @truongnat. I am having the same problem. Since you closed the issue i wanted to ask if you resolved this?

**Comment by truongnat** [comment]
@santosh898 I have resolved it.

- Because error from lib [SnoreToast](https://github.com/KDE/snoretoast), i found PR fix it.

- Step 1:  you can download the source code snoretoast
- Step 2:  modify code with PR above.
- Step 3:  Re-build and move file build <snore-toast-64.exe or snore-toast-32.exe> to your project.

**Comment by santosh898** [comment]
Thank you
