### ISSUE TITLE
Timeout on macOS

### ISSUE THREAD

**Issue by lucasriondel** [mikaelbr/node-notifier#434]
I'm trying to use node-notifier to display notifications on macOS but it fails everytime.

I've tried with a NotificationCenter, without, nothing work, it always timeouts. 

Here's a few samples: 

```
const NotificationCenter = require("node-notifier").NotificationCenter;
var notifier = new NotificationCenter({
  withFallback: false, // Use Growl Fallback if <= 10.8
  customPath: undefined, // Relative/Absolute path to binary if you want to use your own fork of terminal-notifier
});

notifier.notify(
  {
    title: "test",
    message: "test",
  },
  function (err, response, metadata) {
    console.log({ err, response, metadata });
    // Response is response from notification
    // Metadata contains activationType, activationAt, deliveredAt
  }
);
```

logs: 
```
{
  err: null,
  response: 'timeout',
  metadata: {
    activationType: 'timeout',
    activationAt: '2023-05-22 12:36:43 +0200',
    deliveredAt: '2023-05-22 12:36:33 +0200'
  }
}
```

<img width="484" alt="CleanShot 2023-05-22 at 12 37 24@2x" src="https://github.com/mikaelbr/node-notifier/assets/7773454/88ca277b-6d81-4f2e-907c-dc447cc3d347">

![CleanShot 2023-05-22 at 12 38 23@2x](https://github.com/mikaelbr/node-notifier/assets/7773454/b1c9f92e-6fab-4869-8799-d89969943be1)

Any ideas ?

**Comment by DominicGBauer** [comment]
@lucasriondel how did you solve this?
