### ISSUE TITLE
[SUGGESTION] ..

### ISSUE THREAD

**Issue by NullClock** [mikaelbr/node-notifier#440]
You guys missed the chance to use the name "Nodeifier", which would be pronounced as "notifier"!

(this isn't an issue obvi, i'm just putting out an idea.)

**Comment by mikaelbr** [comment]
I wish I could go back 13 years and be better at puns! Luckily now I'm a father of two and will be better suited for naming things going forward. Thanks for your comment!

**Comment by NullClock** [comment]
No problem at all, lol! Also, wow. I forgot I had created this issue
________________________________
