### ISSUE TITLE
503 Service Unavailable - node-notifier-5.4.5.tgz

### ISSUE THREAD

**Issue by abhikakade** [mikaelbr/node-notifier#443]
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/node-notifier/-/node-notifier-5.4.5.tgz: Request failed \"503 Service Unavailable\"".

tried with npm registry as well getting same error every time.

**Comment by duduc** [comment]
i have the same issue

**Comment by mikaelbr** [comment]
I think yarn registry is a mirror for npm registry and this was caused by service issues on npm. Seems to work as expected now?

**Comment by mikaelbr** [comment]
Closing as no update
