### ISSUE TITLE
Missing LICENSE file in the repo of ver 5.1.2

### ISSUE THREAD

**Issue by itsuki-murata** [mikaelbr/node-notifier#447]
Currently I'm using node-notifier version 5.1.2, but can't find a LICENSE file in the repo of ver 5.1.2.
Could you add the LICENSE file in the repo of ver 5.1.2?
Or is it possible to use the LICENSE file of the latest version as the license for ver 5.1.2?
Thanks in advance.

**Comment by mikaelbr** [comment]
The LICENSE-file from main would be the same as for v5.1.2 as defined in [LICENSE field in manifest file](https://github.com/mikaelbr/node-notifier/blob/v5.1.2/package.json#L36).

**Comment by itsuki-murata** [comment]
Thank you for your reply.
I'll use the license of the latest version as the license for ver 5.1.2.
