### ISSUE TITLE
An unexpected error occurred: "https://registry.yarnpkg.com/node-notifier/-/node-notifier-5.4.5.tgz: Request failed \"503 Service Unavailable\""

### ISSUE THREAD

**Issue by lawrencebaer** [mikaelbr/node-notifier#449]
This message appears during yarn install:

An unexpected error occurred: "https://registry.yarnpkg.com/node-notifier/-/node-notifier-5.4.5.tgz: Request failed \"503 Service Unavailable\""

**Comment by mikaelbr** [comment]
This seems to be issue with registry being down. Nothing to do with package it self
