### ISSUE TITLE
Syntax sugar for notifier.notify

### ISSUE THREAD

**Issue by rioc0719** [mikaelbr/node-notifier#45]
Instead of:
`notifier.notify({message: 'Hi'})`
I think we should be able to use:
`notifier.notify('Hi')`.
The title should be the default - 'Node Notification' or whatever it is on each system.

It's cleaner and gets the point across better. Just my thoughts.

**Comment by mikaelbr** [comment]
Good idea. This is something I do on `gulp-notify`. I accept patches if you have some time to spare. :+1:

**Comment by rioc0719** [comment]
@mikaelbr I submitted a PR to fix this issue, but I left WindowsBalloon alone- I explained why [here](https://github.com/mikaelbr/node-notifier/pull/51#issue-63614340).

**Comment by kurisubrooks** [comment]
Was this ever resolved? @rioc0719 @mikaelbr

**Comment by kurisubrooks** [comment]
I was thinking we could try something like this. In @rioc0719 's pull request, he only states the message (`notifier.notify('message');`), but I was thinking maybe we could read the program's package.json and get the title of the app, and make that the notification's title, aswell as setting the sound = true, amongst other options that can be used.

I'd send a pull request, but i'm afraid i'll break something.

**Comment by mikaelbr** [comment]
We don't need this to be included in the next release, so you can easily just do a PR and I'll review it for you.

**Comment by kurisubrooks** [comment]
I'll see what I can do.

**Comment by mikaelbr** [comment]
Added in #45.
