### ISSUE TITLE
OK sorry for the false positive, I didn't know about the single `&` operator and thought that was the thing which was breaking my build (it went a bit further at the time when using `&&`, but now I notice this is not the issue indeed).

### ISSUE THREAD

**Issue by albert849** [mikaelbr/node-notifier#453]
OK sorry for the false positive, I didn't know about the single `&` operator and thought that was the thing which was breaking my build (it went a bit further at the time when using `&&`, but now I notice this is not the issue indeed).
@
- #_Originally posted by @oleole39 in https://github.com/AykutSarac/jsoncrack.com/pull/@@418#https://github.com/user-attachments/assets/c47063eb-c98a-4493-b10a-f202001bfdaeissuecomment-2422822921_@****

**Comment by oleole39** [comment]
?
