### ISSUE TITLE
how to show 2 or more notifications

### ISSUE THREAD

**Issue by sayanee** [mikaelbr/node-notifier#55]
I'm trying to display 2 or more notifications, but this code displays only one after replacing the previous one.

```
var notifier = require('node-notifier');
var notifier2 = require('node-notifier');

notifier.notify({
  'title': 'My notification',
  'message': 'Hello, there!',
  'wait': true
});

notifier2.notify({
  'title': 'hola!!!',
  'message': 'Hello, there!',
  'wait': true
});
```

![image](https://cloud.githubusercontent.com/assets/413879/7799021/90c8273a-0333-11e5-9ca0-5f67bdc5a358.png)

**Comment by mikaelbr** [comment]
Hi, and sorry for the late response, @sayanee. You can use the option `group` to specify what notifications that should be grouped. This isn't documented directly in the readme, but is only referred to through transitivity for the [terminal-notifier docs](https://github.com/alloy/terminal-notifier/#options)

Example:

```js
var notifier = require('node-notifier');

notifier.notify({
  'title': 'My notification',
  'message': 'Hello, there!',
  'wait': true,
  'group': 1
});

notifier.notify({
  'title': 'hola!!!',
  'message': 'Hello, there!',
  'wait': true,
  'group': 2
});
```

**Comment by sayanee** [comment]
:+1: will try the `group` option!

**Comment by kurisubrooks** [comment]
Hey @sayanee, just checking up to see if you got this to work?

**Comment by sayanee** [comment]
I did not quite get the 2 notifications to pop up separately for the same program, but it's how OSX notification style works and nothing to do with `node-notifier`. Hence, I'm closing this.

Thanks :+1:
