### ISSUE TITLE
click on notify

### ISSUE THREAD

**Issue by vinnitu** [mikaelbr/node-notifier#56]
I have ubuntu x64 14.04
use
wait: true
subscribe on 'click'

but can't click because window becomes translucent

**Comment by mikaelbr** [comment]
Are you using notify-send? See https://github.com/mikaelbr/node-notifier#usage-notifysend. I'm afraid that notify-send doesn't support the wait keyword.

**Comment by vinnitu** [comment]
i have something like this
```javascript
var notifier = require('node-notifier');
notifier.on('click', function (notifierObject, options) {
  // Happens if `wait: true` and user clicks notification
});

...

notifier.notify({
        title: 'title',
        message: 'message',
        wait: true
 });
```

not notifySend

**Comment by mikaelbr** [comment]
But you are using `ubuntu x64 14.04`? That, by default, uses the `notify-send` (or sometimes called `notify-osd`) on Ubuntu. Unless you have something else installed, like growl, it doesn't support wait (due to `notify-send`).

**Comment by vinnitu** [comment]
oh, I see, it means I use notify-send by default, so I can use wait flag? :(

**Comment by mikaelbr** [comment]
I haven't found a way for `notify-send` to support wait, yet. You might find a "Growl for Linux" (google this) application which allows you to use wait, though.

**Comment by rishabh1403** [comment]
@vinnitu were you able to make it work using any growl for linux ? If yes, could you please point me in a right direction, Thanks!!!
