### ISSUE TITLE
hangs within tmux session

### ISSUE THREAD

**Issue by timoxley** [mikaelbr/node-notifier#61]
`node-notifier` doesn't seem to work within a `tmux` session, while it works just fine outside of `tmux`. 

`node-notifier` simply never responds, have to kill the process.

### Works outside tmux
![840784fd6d57cc9247f247e757d76f01](https://cloud.githubusercontent.com/assets/43438/8512910/db1f455e-2389-11e5-90fd-e8e21b924f19.gif)
edit: uploaded wrong gif

### Locked up inside tmux
![77791d904a94089b55043dead7c4f676](https://cloud.githubusercontent.com/assets/43438/8512886/4ad9c618-2389-11e5-82b6-067ad6e2a975.gif)

Any clues as to why?

* OSX Yosemite 10.10.4 (14E46)
* iojs 2.3.1
* tmux 2.0

Possibly related https://github.com/mikaelbr/node-notifier/issues/47

**Comment by timoxley** [comment]
Very similar issue here: https://github.com/julienXX/terminal-notifier/issues/115

**Comment by timoxley** [comment]
Investigated, successfully followed instructions in https://github.com/julienXX/terminal-notifier/issues/115#issuecomment-104214742.

![e80c68d863d38a98ff26aa8444e28508](https://cloud.githubusercontent.com/assets/43438/8512997/f610db7c-238c-11e5-9246-af90b8485b09.gif)

Already had the tmux.conf lines, but wasn't working, not sure I recall ever installing `reattach-to-user-namespace` in the first place, but doing a `brew update && brew install reattach-to-user-namespace` fixed the issue.

**Comment by kjarnet** [comment]
Thanks! Had the same issue and this fixed it for me. Wish the readme said something about this, though, as it would've saved me some hours of troubleshooting.

**Comment by mikaelbr** [comment]
[Fixed](https://github.com/mikaelbr/node-notifier#use-inside-tmux-session). Thanks for the heads up and the investigation! :+1:

**Comment by kjarnet** [comment]
Great! Thanks for the awesome plugin :)
