### ISSUE TITLE
Process terminates dispite wait: true on ubuntu14/xfce4-notifyd

### ISSUE THREAD

**Issue by flashhhh** [mikaelbr/node-notifier#63]
Here is code I run:

    import notifier from 'node-notifier';
    notifier.notify({
      title: 'Test',
      message: 'Test mess',
      wait: true
    }, (err, response) => {
      console.log(err);
      console.log(response);
    });
    
    notifier.on('click', (obj, options) => {
       console.log(options);
    });
    
    notifier.on('timeout', (obj, options) => {
       console.log(options);
    });

The problem is that the node process terminates immediately while notification is displayed on the screen, so I can't trigger `click` event.

I don't know if it's a `node-notifier` problem itself but I tried out a lot of solutions (even `growl-for-linux` and it still doesn't work.)

**Comment by mikaelbr** [comment]
Hi! I'm afraid the [notify-send command doesn't support wait](https://github.com/mikaelbr/node-notifier#usage-notifysend).

I haven't tried growl for linux my self, but if it implements the Growl Notification Transfer Protocol (GNTP), which it seems as it does, it should support wait. You could try printing out the command created by `node-notifier` and run it manually through your terminal to see if that works with growl.

**Comment by flashhhh** [comment]
Thanks, @mikaelbr! I'll dig deeply in system aspects of how notifications works in linux.
