### ISSUE TITLE
Support for Win10 Notification Center

### ISSUE THREAD

**Issue by subesokun** [mikaelbr/node-notifier#65]
Is it planned to support also the new Win10 Notification Center? That'd be awesome!

**Comment by mikaelbr** [comment]
I haven't had the chance to fix it, as I don't have Win10 yet (in the process of getting it). See https://github.com/mikaelbr/gulp-notify/issues/90

**Comment by subesokun** [comment]
Great, looking forward to it :) If I can help you with testing just let me know.

**Comment by mikaelbr** [comment]
Thanks! I think I'll potentially have to re-write `toaster` (windows app) to support Windows 10, so I'll let you know if/when I need someone else to test it out!

**Comment by subesokun** [comment]
I see, sounds like a bigger task but looking forward to it. Thanks for your efforts! The features mentioned [in the MSDN blog](http://blogs.msdn.com/b/tiles_and_toasts/archive/2015/07/02/adaptive-and-interactive-toast-notifications-for-windows-10.aspx) sounds very interesting :)

**Comment by mikaelbr** [comment]
Apparently it's a configuration option: https://github.com/mikaelbr/gulp-notify/issues/90#issuecomment-129333034

**Comment by fritx** [comment]
:+1: won't work on win10

**Comment by mikaelbr** [comment]
It seems to be working if you follow the steps from https://github.com/mikaelbr/gulp-notify/issues/90#issuecomment-129333034

**Comment by fritx** [comment]
![image](https://cloud.githubusercontent.com/assets/6647633/9411076/87ae554e-4856-11e5-83ed-72fe24b607bc.png)
I can't find the 'toast' app from the list.. except there is an 'nw-sample-demos' which is relevant

**Comment by fritx** [comment]
the electron provides a new api for windows: displayBalloon, and my app works with it now

**Comment by kurisubrooks** [comment]
Support for Windows 10 is touch and go. The notifications show up fine, but they don't show up in action center.

**Comment by adam-lynch** [comment]
>Support for Windows 10 is touch and go. The notifications show up fine, but they don't show up in action center.

I've had this happen myself with plain node-notifier. 

The latest release of our app uses node-notifier@4.0.3 with a custom `.exe` passed (we forked [nels-o/toaster](https://github.com/nels-o/toaster) so we could have our own app icon) and that doesn't show the notification normally but it does show in the Action Center. I don't know what's going on with it.

**Comment by jg123** [comment]
Looks to be a bug in Windows 10 for win32 apps posting toast notifications. See here:
http://stackoverflow.com/questions/31962216/unexpected-behaviours-in-toast-notification-from-desktop-app-in-windows-10
and here:
http://blogs.msdn.com/b/tiles_and_toasts/archive/2015/07/02/adaptive-and-interactive-toast-notifications-for-windows-10.aspx#10634761

You can get the toast in the action center if you click the "X" on the toast notification.

**Comment by fritx** [comment]
:fearful: :

**Comment by MadLittleMods** [comment]
The Window 10 toast notifications worked fine for me without any manual action. This is how it shows up in the notification center:

![](http://i.imgur.com/xS5w1P6.png)
