### ISSUE TITLE
how to get message from server?

### ISSUE THREAD

**Issue by prugel** [mikaelbr/node-notifier#66]
I spent almost one day. please help me.

I have ubuntu server (192.168.0.104)
I use win 7 laptop (192.168.0.100), and install growl for window.

test code on laptop. growl display message.
```
var Growl = require('node-notifier').Growl;

var notifier = new Growl({
  host: 'localhost', // '192.168.0.100',
  port: 23053
});

notifier.notify({
  title: 'Foo',
  message: 'Hello World'
}, function(error, response) {
  console.log(error);
  console.log(response);
});
```

but this code does not work in ubuntu.
```
[Error: Couldn't connect to growl (might be used as a fallback). Make sure it is running]
```
How do I get message form ubuntu?
```
var Growl = require('node-notifier').Growl;

var notifier = new Growl({
  host: '192.168.0.100',
  port: 23053
});

notifier.notify({
  title: 'Foo',
  message: 'Hello World'
}, function(error, response) {
  console.log(error);
  console.log(response);
});
```

**Comment by mikaelbr** [comment]
Your syntax looks right to me. Have you checked if you can communicate with growl? That port's are open and everything on that end is fine.

[As seen in the code](https://github.com/mikaelbr/node-notifier/blob/master/notifiers/growl.js#L33), host and port are set. You can also try running [growly](https://github.com/theabraham/growly) directly to see if that works. I have a feeling this is more a problem with network connectivity.

**Comment by prugel** [comment]
growly work fine. good.
```
var growly = require('growly');

growly.setHost('192.168.0.100', 23053);
growly.notify('This is as easy as it gets', { title: 'Hello, World!' });
```

below code does not call [growl](https://github.com/mikaelbr/node-notifier/blob/master/notifiers/growl.js#L33)
```
var Growl = require('node-notifier').Growl;

var notifier = new Growl({
  host: '192.168.0.100',
  port: 23053
});

notifier.notify({
  title: 'Foo',
  message: 'Hello World'
}, function(error, response) {
  console.log(error);
  console.log(response);
});
```

**Comment by prugel** [comment]
and below code does not call [growl.notify](https://github.com/mikaelbr/node-notifier/blob/master/notifiers/growl.js#L33)

```
var notify = require('gulp-notify');

notify.onError({
  title: 'Foo',
  message: 'Hello World',
  host: '192.168.0.100',
  appName: 'Foo',
  port: '23053'
});
```

**Comment by mikaelbr** [comment]
Ah, you're right. The code check's if you have growl locally (an faulty implementation). [`checkGrowl()`](https://github.com/mikaelbr/node-notifier/blob/master/lib/checkGrowl.js) should be extended.

For now, you can avoid this by activating `wait`.

```js
var notify = require('gulp-notify');

notify.onError({
  title: 'Foo',
  message: 'Hello World',
  host: '192.168.0.100',
  appName: 'Foo',
  wait: true,
  port: '23053'
});
```

**Comment by prugel** [comment]
I think checkGrowl is not need. Because growly return callback.
[edited code](https://github.com/prugel/node-notifier/commit/1a65c5e3cc05726628ccafb9cfb26da13d67a4c4)

and gulp-notify 
[edited notify.js](https://github.com/prugel/gulp-notify/commit/3065406e6e47eee7ad82cb8d514ed3e72e6643ed)
[edited extra_api.js](https://github.com/prugel/gulp-notify/commit/d26438c1aad9ee33808ffb21e22c5e8320d6b6b5)

It works now.

**Comment by mikaelbr** [comment]
Thanks! `checkGrowl` was originally implemented to give better feedback to the user on what error occurred. Especially on "fire and forget" mode, where you don't wait for the response. I think a better solution is to extend `checkGrowl` to take a host and port as well.
