### ISSUE TITLE
Extremely weird behavior 

### ISSUE THREAD

**Issue by 462960** [mikaelbr/node-notifier#67]
I'd like to inform about extremely strange behavior of "sass-notify":
1) Some mistakes play exactly as  expected and written in RED. (For example: missed semicolon after "text-indent: 100%;" )
2) Some mistakes went completely unnoticed. (For example: missed semicolon after "overflow: hidden; " )
3) Some mistakes play without notification and written in WHITE. (For example unbound variable)
![sass error](https://cloud.githubusercontent.com/assets/10447862/9682636/28fb527a-5311-11e5-97e0-9d09194c5904.png)

I run Win7 and had installed Growl, as recommended.
The behavior pattern is exactly the same, in this case, but notifications come from Growl...

**Comment by mikaelbr** [comment]
Hi and thanks for your issue! This seems to me as a issue with the sass implementation you are using. gulp-notify simply listens to error event and show notification from that, if the plugin you are listening to doesn't emit error, no error will be caught.

**Comment by 462960** [comment]
Thanks for response and for the plugin as well. I'll keep my eye on it. The behavior pattern has changed after some period of time but for now, thanks to your answer, I do know the root of mistake.

**Comment by kurisubrooks** [comment]
Hey @462960, just checking up to see if you've found the cause of the problem / fixed it.

**Comment by 462960** [comment]
Thanks for caring. The problem has gone and I haven't idea what way. Seems it had faded after OS reboot.

**Comment by kurisubrooks** [comment]
Interesting.. Thanks for the follow up.
Please let us know if this happens again and i'll be happy to reopen the issue for you.
