### ISSUE TITLE
Windows 10 shows console window

### ISSUE THREAD

**Issue by naueramant** [mikaelbr/node-notifier#68]
In windows 10 toaster.exe shortly shows a window when executed. Can this in some way be disabled? Or make the window hidden?

**Comment by kurisubrooks** [comment]
I've seen this with other Windows programs in Windows 10, so i'm unsure if this is Toaster exclusive. However, you should make this an issue with the dependant module, not with node-notifier itself. 
https://github.com/nels-o/toaster
