### ISSUE TITLE
Is there any straight forward way to connect this with BrowserWindow notifications with Electron on Windows?

### ISSUE THREAD

**Issue by lipis** [mikaelbr/node-notifier#69]
So notifications work out of the box on OS X, [but not on Windows](https://github.com/atom/electron/issues/262).

I managed to display show notifications on demand (with `WindowsToaster` but it could be with anything I guess) but how could we connect that with the notifications that are coming from the [`BrowserWindow`](https://github.com/atom/electron/blob/master/docs/api/browser-window.md)?

**Comment by mikaelbr** [comment]
I'm unsure what you mean. I've never used electron to a big extent, and don't know what you mean with connecting notifications from `BrowserWindow` to `node-notifier`.

Are thinking of using `node-notifier` as a fallback for electron notifications on Windows? In that case I'd say the best way would be to make your own abstraction of notification on top of Electron (just a function) that checks if you're on Windows or not. If on windows, use node-notifier.

Or you could just use `node-notifier` and let it handle all fallbacks and platform checking.

**Comment by lipis** [comment]
I was hoping to be able to subscribe somehow when the notification is being fired.. but it's not doable so I'll close this one for now. Thanks.

**Comment by seriema** [comment]
@lipis I created [electron-notification-shim](https://github.com/seriema/electron-notification-shim) for exactly that purpose. It's really easy to use, just subscribe to `notification-shim` events in your main process. Bounce them back to the view if you want with the events `returnValue` or `sender.send()`.

**Comment by lipis** [comment]
Will check at one point.. thanks.
