### ISSUE TITLE
How can I send custom options, so I could read them on click?

### ISSUE THREAD

**Issue by lipis** [mikaelbr/node-notifier#70]
So lets say I want to have a `custom_id` (or some `data` object) with a particular notification that later I would like to retrieve it when the user is going to click on it. Is it possible somehow?

```js

var data  = {
  'foo': 'bar',
  'hello: 'world
}

notifier.notify({
  title: 'My awesome title',
  message: 'Hello from node, Mr. User!',
  custom_id: 1234567, // Some custom ID
  data: data, //Some more data
}, function (err, response) {
  // response is response from notification
});

notifier.on('click', function (notifierObject, options) {
  console.log('Custom ID', options.custom_id);
});
```

**Comment by mikaelbr** [comment]
As far as I know, this should be possible already, no?

Here is where `click` is triggered: https://github.com/mikaelbr/node-notifier/blob/master/lib/utils.js#L170
It passes on `options` as passed into notify, so it should work as you outline above.

**Comment by lipis** [comment]
It worked as expected.. not sure what went wrong in my earlier tests..! :+1:

**Comment by mikaelbr** [comment]
Great! Glad it worked out.

**Comment by lipis** [comment]
So far so good :) Great job..
