### ISSUE TITLE
Why do I see the default terminal icon when I'm setting my own? (OS X)

### ISSUE THREAD

**Issue by lipis** [mikaelbr/node-notifier#71]
This happens on OS X (didn't test other platforms) when I'm not have the `icon` option:
<img width="349" alt="screen shot 2015-10-07 at 11 31 41" src="https://cloud.githubusercontent.com/assets/125676/10333908/2135c40e-6ce7-11e5-8e69-ca0e21140ffa.png">

and when I have it:
<img width="339" alt="screen shot 2015-10-07 at 11 32 05" src="https://cloud.githubusercontent.com/assets/125676/10333909/22d1b6b0-6ce7-11e5-9189-d884348e2b1d.png">

Am I missing something? How could I get rid of the terminal icon next to the title?

```
  notifier.notify({
    title: 'Title',
    message: 'Hello, world!',
    icon: 'path/to/image.png,
  }, function(error, response) {
    console.log('error', response);
  });
```

**Comment by adrienaggery** [comment]
Same issue here.
Haven't found any solutions

**Comment by mikaelbr** [comment]
No, I'm afraid that's how the notification work, as it's the terminal that initiates the message. The only way to avoid this is to use your custom `terminal-notifier` where the Terminal icon is swapped for your own. It's not a big task, and you can easily [set `customPath`](https://github.com/mikaelbr/node-notifier#all-notification-options-with-their-defaults) for notification center reporter.

**Comment by kurisubrooks** [comment]
This happens because of the way notifications in OS X work. The notification will show the referring app icon, and because we're using [terminal-notifier](https://github.com/julienXX/terminal-notifier) to push notifications, we have the icon of terminal-notifier.

To work around this, you'll need to compile terminal-notifier with your own app.icns. Download the source, change out the AppIcon bundle with your own in Xcode, recompile terminal-notifier and pop it into node-notifier. (`/node-notifier/vendor/terminal-notifier.app`)

Now that you have your own terminal-notifier inside node-notifier, remove all the `icon` references from your OS X Notification Center code, and run the notification as if it has no icon. If the old app icon is showing in your notifications, you need to clear your icon cache. (Google how to do this)

Ping me for any follow up questions~

**Comment by kurisubrooks** [comment]
Let me know if this works for you, @lipis

**Comment by lipis** [comment]
Thanks @kurisubrooks but I won't try it at the moment, since that wasn't urgent and it looks like it's not that straight forward. The Notifications API works nicely on OSX so I'll rely on this one now..

**Comment by zimo888** [comment]
If the old app icon is showing in your notifications,Change build version. Change bundle identifier fixed it

**Comment by averissimo** [comment]
If you are running a packaged electron app, you need to have the `CFBundleIdentifier` value in the Info.plist equal to the `sender` property when calling `notifiy`

we just experienced this when building the OSX app with yakyak. they didn't match and the terminal started appearing.

**Comment by mbushpilot2b** [comment]
@kurisubrooks I have built my own version with my app icon, the app icon shows up.
<a href="http://imgur.com/OiFfAG6"><img src="http://i.imgur.com/OiFfAG6.png" title="source: imgur.com" /></a>

But even then its not working? I don't know how to clear cache? in my electron application or where? thank you!

**Comment by mbushpilot2b** [comment]
Here is a step by step:
1. Clone or download https://github.com/mikaelbr/terminal-notifier
2. download xcode
3. delete Terminal.icns inside of terminal-notifier folder (empty trash too.)
4. drag in your apps .icns inside of terminal-notifier folder. (dont know how to make a .icns? Use .png to .icns converter: https://iconverticons.com/online/)
5. open Xcode project file inside terminal-notifier folder
6. change Bundle identifier: nl.superalloy.oss.${DIAMOND:rfc1034identifier} to nl.superalloy.oss.${WHATEVERYOURAPPNAMEIS:rfc1034identifier} my app name happened to be diamond.
<a href="http://imgur.com/lGi4TQy"><img src="http://i.imgur.com/lGi4TQy.png" title="source: imgur.com" /></a>
7. also for good measure i changed the bundle and bundle version to random numbers of my choosing.
8. this is the magic: change iconfile to the NAME of the .icns that you included in the terminal-notifier folder in step 4.
9. Now CLEAN the project before building. Cmd + Shift + K 
10. then build Cmd + Shift + B
11. to find the built app in xcode right-click on: 
<a href="http://imgur.com/o2Bt8GX"><img src="http://i.imgur.com/o2Bt8GX.png" title="source: imgur.com" /></a>
and select "Show In Finder"

12. copy that to replace your old terminal-notifier.app in your project folder which should be inside of your yourProjectName/node_modules/node-notifier/vendor/terminal-notifier.app
13. you can check to see if the new icon works by double clicking on the terminal-notifier.app and a notification should show up with your new icon! 

THEN you have to USE the custom path when calling for a notification in electron so it uses your version and not OSX's. This worked for me: http://stackoverflow.com/questions/35002117/remove-terminal-icon-in-node-notifier go to ifedapo olarewaju answer!

**Comment by fritx** [comment]
Another quick solution here (inspired by @mbushpilot2b):

1. install node-notifier normally

    ```plain
    npm install node-notifier
    ```

2. hack assets of terminal-notifier

    ```plain
    cd node_modules/node-notifier/vendor
    cd terminal-notifier.app/Contents
    sed -i 's/terminal-notifier/genius-notifier/g' Info.plist  # replace identifiers
    sed -i 's/Terminal/Genius/g' Info.plist  # replace icon
    rm Resources/Terminal.icns  # remove the original icon
    cp my/resource/Genius.icns Resources/Genius.icns  # replaced by our own icon
    ```

**Comment by tolgaergin** [comment]
hey @fritx Thanks for quick solution. 
Is there any missing step left? After I did what you wrote, I can't see any notification but the listeners such as timeout is working.

**Comment by dennispassway** [comment]
You can fake sending from another application (which changes the icon and removes it from the title by setting the sender:

```javascript
notificationCenter.notify({
  message: 'Test',
  sender: `com.electron.${app.getName()}`,
  title: APPLICATION_TITLE,
  wait: true
})
```

**Comment by fritx** [comment]
@tolgaergin hey, did you replace the icns with an existing one of your own?

**Comment by GeorgeBgk** [comment]
Here's a quick guide how to do it. (If you don't have an ICNS file, here's a [converter](https://iconverticons.com/online/))

1. Navigate to `node_modules/node-notifier/vendor`
2. Rename your custom icon into `Terminal.icns`
3. Right-click `terminal-notifier` file and click `Show Package Contents`
4. Navigate to `Contents/Resources`
5. Replace `Terminal.icns` file with your own
![ezgif-2-637e763ed9](https://cloud.githubusercontent.com/assets/11464592/26460221/a709ee96-4181-11e7-800e-1f692a57a2e4.gif)

Here you go! Hope this helps.

**Comment by fritx** [comment]
@GeorgeBgk oops, I don't think it is a good idea to replace Terminal.icns directly,
without replacing identifiers in plist mentioned at https://github.com/mikaelbr/node-notifier/issues/71#issuecomment-288992882.

It seems that would cause other apps on your computer, which are using node-terminal as well, to show the replaced icon, not the original one. That would be confusing.

**Comment by GeorgeBgk** [comment]
@fritx You are incorrect. I replace Terminal.icns only in my project. It does not affect others, I tested

**Comment by yourfavorite** [comment]
@GeorgeBgk I tried your method and my electron app still shows the terminal icon. Is there some cache clean command I need to run?

**Comment by rien333** [comment]
My personal solution is to create an application with a fully transparent icon, and call it's sender ID with `-sender` flag.

**Comment by djalmaaraujo** [comment]
@rien333 can u show some code?

**Comment by rien333** [comment]
idk, nothing too fancy: `terminal-notifier -message 'hi' -title  "$(date +"%H:%M")" -appIcon img.jpg -sender 'rw.EmptyApp'` The actual important is creating an app with the bundle identifier 'rw.emptyApp' (or any bundle ID of your choosing) with for example Xcode. Google can surely show you how.  I think some of the spacing is off tho somewhere (the title field maybe?) but it does avoid the icon.

**Comment by code-with-sam** [comment]
For anyone who finds their way to this issue. I found this script from 'vitorgalvao/tiny-scripts' which had since been removed from the repo. I brought it back to life incase it can help anyone else here.

https://github.com/code-with-sam/customise-terminal-notifier

**Comment by damianobarbati** [comment]
Oh no! Did anybody find a solution to this?

Having to create a window+renderer just to show a notification is crazy :\

**Comment by GeorgeBgk** [comment]
Just customize terminal-notifier icns file.
https://github.com/mikaelbr/node-notifier/blob/master/vendor/terminal-notifier.app/Contents/Resources/Terminal.icns

**Comment by laxmikanta415** [comment]
This solved my problem and you only need to have your icns file ready: 

run this command in terminal  after downloading :customise-terminal-notifier 

** path/customise-terminal-notifier-master/customise-terminal-notifier -i path/Terminal.icns  -b com.bundle.identifier

**Comment by Ivorfason** [comment]
It worked with custom icon.... But the click event doesn't response....

**Comment by Aarbel** [comment]
Do anyone has a solution to thru electron and electron builder ? 

Changing directly the files in node modules isn't really a stable solution

**Comment by gbougakov** [comment]
Rebuild terminal-notifier, point node-notifier to rebuilt binary.

**Comment by Aarbel** [comment]
@gbougakov do you have more details ? I saw your post: https://github.com/mikaelbr/node-notifier/issues/71#issuecomment-304057970 ;)

We don't want to make this procedure each time we install our node_modules.

**Comment by gbougakov** [comment]
@Aarbel Sorry for that post. It is horrible, has a lot of caveats, do not follow it.

`node-notifier` uses [`terminal-notifier`](https://github.com/julienXX/terminal-notifier) under the hood to send notifications on macOS.

First, clone the [`terminal-notifier` repo](https://github.com/julienXX/terminal-notifier), open the Xcode project, replace `Terminal.icns` and rebuild the project. Under `Products` you'll find `terminal-notifier.app`, copy it to your project directory.

When initialising `NotificationCenter`, specify path to `terminal-notifier.app` like so:
```js
const notifier = new NotificationCenter({
  customPath: 'path/to/terminal-notifier.app'
})
```

That's it!

**Comment by Aarbel** [comment]
@gbougakov 

Didi you faced this error ? 

![image](https://user-images.githubusercontent.com/25119847/56096481-f3f73980-5ee8-11e9-88b9-b0bd136de703.png)

![image](https://user-images.githubusercontent.com/25119847/56096484-fd80a180-5ee8-11e9-93d2-8004133444ab.

**Comment by BluFenix00** [comment]
i could change the icon but the click is not working, and i can't se extra buttons

**Comment by BluFenix00** [comment]
@Aarbel your path is wrong, inside the terminal-notifier.app is /Contents/MacOS/terminal-notifier

**Comment by Aarbel** [comment]
@BluFenix00 i just left `node-notifer` to basix `new Notification` api for Electron. works like a charm, no extra tricks to do during hours :)

**Comment by Aarbel** [comment]
About `click` event i've made this PR to provide a slightly better doc : https://github.com/mikaelbr/node-notifier/pull/274/files

**Comment by BluFenix00** [comment]
i could resolve all my problems but when i install my app in another computer the icon look with a forbidden icon overriding it, but in my computer it look fine.
<img width="162" alt="Screen Shot 2019-04-15 at 5 42 41 PM" src="https://user-images.githubusercontent.com/20652878/56167619-a4774300-5fa6-11e9-9cac-1dc007844400.png">

**Comment by Aarbel** [comment]
With `node-notifier` ? 
If you continue to face problems with this library, just use the standard api inside Electron renderer process, and without any library: https://developer.mozilla.org/en-US/docs/Web/API/notification

**Comment by BluFenix00** [comment]
the problem was the version of terminal-notifier, if you want to try the process of replace the icon with xcode, make sure that you are working on terminal-notifier 1.7.2

**Comment by zquancai** [comment]
> With `node-notifier` ?
> If you continue to face problems with this library, just use the standard api inside Electron renderer process, and without any library: https://developer.mozilla.org/en-US/docs/Web/API/notification

It had a question that the notification can't show a close button when hover. like below:
<img width="350" alt="Screenshot 2019-12-18 at 11 31 09 AM" src="https://user-images.githubusercontent.com/8609783/71053599-eab22100-2189-11ea-9bc4-06f518b535a1.png">

**Comment by newCodeRunner** [comment]
Anyone using electron builder and node-notifier and still facing this issue, here are quick easy solutions below:

In your electron main process:
`
import notifier from 'node-notifier';

notifier.notify({
      sound: true,
      title: 'My Title',
      message: 'My Message in body',
      icon: 'My Absolute path to icon (after app has been built',
      contentImage: 'My Absolute path to icon (after app has been built',
      appID: 'MyApp',
})
`

You also need to configure electron builder build config as below:

`
asarUnpack: ['node_modules/node-notifier/vendor/'],
extraResources: [
 {
   from: 'src/relative/path/to/directory/with a "Terminal.icns" file',
   to: 'app.asar.unpacked/node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/Resources',
   filter: ['*.icns'],
 },
],
`

**Comment by mayeaux** [comment]
> @georgebgk
> Navigate to node_modules/node-notifier/vendor
> Rename your custom icon into Terminal.icns
> Right-click terminal-notifier file and click Show Package Contents
> Navigate to Contents/Resources
> Replace Terminal.icns file with your own
> Open terminal-notifier/Contents/Info.plist
> 
> The most important things are the next two steps.
> **Change the build version to anything.**
> **Change the bundle identifier to anything.**

Worked for me thanks.

For reference, the two keys you have to change are
`<key>CFBundleIdentifier</key>`
`<key>CFBundleVersion</key>`
