### ISSUE TITLE
[Win32] Click event should be also fired even with the wait set to false.

### ISSUE THREAD

**Issue by lipis** [mikaelbr/node-notifier#72]
I think the following should happen regardless of the `wait` option and should always send the event if the user clicks on the notification. Works like this on OS X, but on Windows 10 it doesn't do anything unless `wait: true`.

It would be nice to be able to react if the user managed to click on the notification before the timeout.

``` js
notifier.on('click', function (notifierObject, options) {
  // Happens if 'wait: true' and user clicks notification
});
```

**Comment by mikaelbr** [comment]
How does this work now in master branch when switching toaster. Could someone please test out by doing:

```
npm i mikaelbr/node-notifier
```

**Comment by mikaelbr** [comment]
After further thought, I'm afraid this isn't possible. The wait flag sets to the toaster application to not return immediately. Without it set, the CLI will exit with exit code 0 before being able to say wether or not a user interacted with the notification.
