### ISSUE TITLE
Toaster size

### ISSUE THREAD

**Issue by Mosho1** [mikaelbr/node-notifier#74]
I'm using the default windows (8.1) toaster, and I would like to make it taller so that the text fits. Is this possible?

**Comment by kurisubrooks** [comment]
No, this is not possible. The only way to do this would be to add whitespace to the notification. (Adding lines before/after the message). The notification takes the height of the content.

**Comment by kurisubrooks** [comment]
Might want to close this one @mikaelbr

**Comment by mikaelbr** [comment]
@kurisubrooks You can do it yourself :smile: I've added you as a collaborator to the project.

**Comment by kurisubrooks** [comment]
I saw! Thanks :smile:
