### ISSUE TITLE
Suggestion: Fail quietly if no notifiers are installed

### ISSUE THREAD

**Issue by jingchan** [mikaelbr/node-notifier#8]
Getting "ECONNREFUSED" errors on my Windows 8.1 machine when growl for windows is not installed.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

It'd be nice to preserve gulp-notify's console output functionality while making external notification programs optional.  (E.g. I'm a fan of the notification systems available on OS X, but am not a fan of Growl for Windows.)

So far I've hacked around it by adding:

```
.on('error', function(e){
  console.log("No notification center found");
})
```

**Comment by scythargon** [comment]
Hello! It would be great if there would be an option to disable the console print of error message also T_T

**Comment by mikaelbr** [comment]
Hi! You can disable gulp-notify on specific environments [using env vars](https://github.com/mikaelbr/gulp-notify#disable-gulp-notify). Hope this helps.

**Comment by scythargon** [comment]
Yup, that was what I went with, thank you. Just forgot that I have to use `gulp-if` not just `if`.

**Comment by mikaelbr** [comment]
In a stream, you'll need to use `gulp-if` to opt in a "blank stream", yeah.
