### ISSUE TITLE
notifu/balloon doesn't work on 32bit windows

### ISSUE THREAD

**Issue by kurisubrooks** [mikaelbr/node-notifier#80]
Originally brought to our attention in #76, i've decided this needs it's own seperate issue, to track progress and everyone's thoughts.

Original message:
> Hey @kurisubrooks just an update on the Win7 Balloon problems I was having. Finally got around to get a debug of the code and was receiving the error

>```
"Error: ENOENT, node_modules/node-notifier/vendor/notifu/notifu not found in ..MyApp/resources/app.asar"
```

>So I took a look in the balloon.js and notice it was looking for ".../notifu/notifu" which I assume is to handle the regular .exe and the 64.exe. For this we are only building a 32 bit version, so I changed the .js to notifu.exe and it fixed the problem.

> Not sure if this will help fix the problem if you need x32 & x64, but just wanted to let you guys know. Thanks! 
> – @sean6bucks

**Comment by ErikBean** [comment]
+1

**Comment by eduardostuart** [comment]
+1

**Comment by mikaelbr** [comment]
I don't have access to Windows 7 any more. Could someone try out the branch and see if this issue is fixed?

Install by doing:

```
npm install mikaelbr/node-notifier#notifuArch
```

**Comment by kurisubrooks** [comment]
@mikaelbr — Tested against Windows 7 32-bit. Works :+1:
