### ISSUE TITLE
"Notifu" package appears to be infected.

### ISSUE THREAD

**Issue by iowillhoit** [mikaelbr/node-notifier#86]
We run [ClamAV](http://www.clamav.net) nightly on our servers. Last night we had 13 reports of malicious `notifu.exe` files. 

Our `notifu.exe` files have not been modified for a while, I would guess that ClamAV just added a check for this worm last night. 

Example Reports:
```
/home/USERNAME/www/wp-content/themes/Sun/node_modules/gulp-notify/node_modules/node-notifier/vendor/notifu/notifu.exe: Win.Worm.Chir-2815 FOUND
/home/USERNAME/www/api/node_modules/laravel-elixir/node_modules/gulp-notify/node_modules/node-notifier/vendor/notifu/notifu.exe: Win.Worm.Chir-2815 FOUND
```

I did a quick search and found that apparently this file is known to be malicious:
https://www.reasoncoresecurity.com/notifu.exe-22a6a9191ea8c6d7cc6ee552e8dfda485e53c1ed.aspx

Notice the "Common path":
`C:\users\{user}\appdata\local\temp\{random}.tmp\node_modules\node-notifier\vendor\notifu\notifu.exe`

I ran `openssl sha1 [file]` on every `notifu.exe` to get a checksum and they returned one of two results. Neither of which is listed on the reasoncoresecurity.com site above.
```
ec1dc5fb10718afb1201ba2ddd4ab69fa62ff1f4
5529988a429a0af159d28260059309db668f0e31
```

I also tried updating node-notifier to 4.4.0, but the SHA1 was the same and ClamAV still reported it malicious.

Please let me know if you need any more information from me.

Thanks

**Comment by kurisubrooks** [comment]
I'm not able to look into this personally, but i've assigned the issue to mikael, hopefully he'll be able to look into this and see to your claims.

**Comment by nobuzz** [comment]
Merry Xmas. Same file, same report, same AV.

.npm/node-notifier/4.3.1/package.tgz: Win.Worm.Chir-2815 FOUND

**Comment by kurisubrooks** [comment]
This is concerning indeed. As it's the holiday season we can't get to this right away, but @mikaelbr should now be aware of the issue and will look into it as soon as he can. I'm unaware of what this worm does, but if you feel that it may cause your systems harm in any way, I recommend you pause any programs with node-notifier for now, or remove the dependency until the issue is sorted.

**Comment by insology** [comment]
Hello, the same was for me. node_modules/laravel-elixir/node_modules/gulp-notify/node_modules/node-notifier/vendor/notifu/notifu.exe: Win.Worm.Chir-2815 FOUND

**Comment by pixelwhip** [comment]
I'm getting the same thing. This thread is the only thing that turns up in a google search for this infection name.

**Comment by sambernard** [comment]
I'm seeing this as well-

```
/home/www/.npm/node-notifier/4.3.1/package.tgz: Win.Worm.Chir-2815 FOUND
/tmp/npm-10475-09e11859/registry.npmjs.org/node-notifier/-/node-notifier-4.3.1.tgz: Win.Worm.Chir-2815 FOUND

node_modules/gulp-notify/node_modules/node-notifier/vendor/notifu/notifu.exe
```

**Comment by insology** [comment]
Also form me after scan of home dir
/home/mattia/.npm/node-notifier/3.4.1/package/vendor/notifu/notifu.exe: Win.Worm.Chir-2815 FOUND
/home/mattia/.npm/node-notifier/3.4.1/package.tgz: Win.Worm.Chir-2815 FOUND

**Comment by lihaibh** [comment]
I downloaded the binary from paralint.com which is the rightful owner of this file, i compared the two versions the one on that repository and theirs and i found no binary difference.
It a c++ opensource and this is the source code: http://src.paralint.com/listing.php?repname=Notifu&path=/trunk/#path_trunk_

It compiled using VS compiler (to be exact Microsoft Visual C++ 9.0 - Visual Studio 2008 (E8)) so i dont think it will ever work on Linux distribution systems though it has execution privileges if you run it, it will fail to work.
I dont think you should be worried, delete this file, dont run composer update on your production environment.

Also i advise you to install rootkit hunter, to find malicious software that an anti virus will have hard time to find, just in case....

**Comment by jdempster** [comment]
It's a false positive in clamAv. I have informed them. It may take some time for them sort. 

No other AV is having this issue. 
https://www.virustotal.com/

/James

**Comment by insology** [comment]
Great! Thank you James!

**Comment by kurisubrooks** [comment]
I've just run it through my everyday antivirus and I have no infections detected. Because it seems to be only coming from one single program, i'm going to rule the possible infection out, and say it's a false positive. If you believe otherwise, please drop a message and i'll try to look into it.

**Comment by iowillhoit** [comment]
Awesome, thanks everyone!

**Comment by flohdot** [comment]
Zillya is still/now marking notifu.exe as infected. Verified using their app directly as well. I contacted their support, it might help if other interested parties do the same. 

https://www.virustotal.com/en/file/511adc6c5f1fdf45cc0e266b7ab052c64f4620fed3c982e23d8e3c2f49c8a818/analysis/1452632219/

**Comment by kurisubrooks** [comment]
Can someone on Windows please run notifu.exe, then check if there are any of the following folders/files exist?

— `%APPDATA%`\install\excel cap.exe
— `%APPDATA%`\microsoft\f68mkaajqqsx.exe

Taken from here https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?Name=Backdoor%3AWin32%2FNetWiredRC.C&ThreatID=-2147275434

**Comment by ixe013** [comment]
I'm Notifu's developer. I heard about this virus report from a user in the field. 

This is a really tiny program, Windows only. It doesn't write anything on the filesystem or connect to any server of any sort. It will read the icon of the parent process by default. Nothing to write home about...

Is there anything I can do to help you sort this out ?

**Comment by kurisubrooks** [comment]
@ixe013 According to the Virus' definition as per Microsoft's Security Knowledgebase, `Backdoor.NetWiredRC` allows backdoor access and control to a user's PC. 

```
This threat can give a malicious hacker access and control of your PC. They can then perform a number of different actions, including:
-Deleting files
-Downloading and running files
-Logging your keystrokes or stealing your sensitive data
-Modifying your system settings
-Running or stopping applications
-Spreading malware to other PCs
-Uploading files
-Connects to a remote host

We have seen this threat connect to a remote host, including:
-tatanajax.ddns.net using port 1010

Malware can connect to a remote host to do any of the following:
-Check for an Internet connection
-Download and run files (including updates or other malware)
-Report a new infection to its author
-Receive configuration or other data
-Receive instructions from a malicious hacker
-Search for your PC location
-Upload information taken from your PC
-Validate a digital certificate
```

I am unsure of how notifu is coded (as I am a node developer), but maybe try triggering a new build from our forked version, or update some of our code, dependencies, whatever you can think of. 

The definition of the virus can be found on Microsoft's website [here](https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?Name=Backdoor%3AWin32%2FNetWiredRC.C&ThreatID=-2147275434).

We'd be appreciative of any help you'd be able to give us.

**Comment by ixe013** [comment]
I also contacted Ziliya, but maybe there is something else happening.

The file hashes posted by @iowillhoit do not match the hashes from my precompiled binaries:
```
$ curl -L http://www.paralint.com/projects/notifu/dl/notifu-1.6.zip | funzip | openssl dgst -md5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0  W ARNING: can't open config file: ././ssl/openssl.cnf
  0 2230k    0 12187    0     0  87049      0  0:00:26 --:--:--  0:00:26 87050
(stdin)= 44fcfec93507fd406389c668f37e0718
```

They do not match the hashes from node-notifier either (tried both 4.4.0 and 4.3.1 versions):
```
$ curl -L https://github.com/mikaelbr/node-notifier/raw/master/vendor/notifu/notifu.exe|openssl dgst -md5
  % Total    % Received % XfWeARNING: can't open config file: ././ssl/openssl.cnf
rd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0    518      0 --:--:-- --:--:-- --:--:--   518
100  239k  100  239k    0     0   365k      0 --:--:-- --:--:-- --:--:--  698k
(stdin)= 44fcfec93507fd406389c668f37e0718
```

Finally, they [do not match Virustotal's hashes](https://www.virustotal.com/en/file/511adc6c5f1fdf45cc0e266b7ab052c64f4620fed3c982e23d8e3c2f49c8a818/analysis/1452632219/) either (MD5 hashes are in the "Additional Information tab").

This is might be far stretch, because the problem was reported by more than one person, but could it be that by some unfortunate event, your node installation was infected by the virus?

If you still have it, please send me the notifu.exe that has the "infected" hashes   
 - `ec1dc5fb10718afb1201ba2ddd4ab69fa62ff1f4`
 - `5529988a429a0af159d28260059309db668f0e31`

I will disassemble and compare with my build.

**Comment by kurisubrooks** [comment]
@ixe013 I just tested my local 32bit executable from my repo fork, and it's retrieved no results.
https://www.virustotal.com/en/file/511adc6c5f1fdf45cc0e266b7ab052c64f4620fed3c982e23d8e3c2f49c8a818/analysis/1452744699/

Here was my hash:
`511adc6c5f1fdf45cc0e266b7ab052c64f4620fed3c982e23d8e3c2f49c8a818`

I wonder if npm is corrupting or adding the backdoors in to the releases?

**Comment by ixe013** [comment]
I very much doubt that npm is corrupting binaries, let alone add executable code to them. 

I installed node-notifier version 4.3.1 and 4.4.0 on my machine and sure enough, the `notifu.exe` that came with them is the original, virus-free version I compiled years ago. The hash you have is the same as mine (if computed with sha256).

What might have happened is that the machines where notifu was flagged as a virus was *already infected*, and it spread to `notifu.exe` when it was run. But then again, why would ClamAV on @iowillhoit  machine report only notifu and not the original infection?

**Comment by kurisubrooks** [comment]
I'm unsure, this is very confusing. 
I'm going to leave the issue closed for now as it's clearly not a problem with notifu nor node-notifier.
Thanks a bunch for your help.

If anyone can come up with any more info or reasoning as to why they may think this might be happening, please let me know and we can look into it.

**Comment by iowillhoit** [comment]
Unfortunately @ixe013, I no longer have the files that produced those hashes, sorry.

**Comment by ixe013** [comment]
Zilia responded to my email (and maybe to others on this thead) and removed the false positive about Notifu.exe. 

The report on Virus Total : https://www.virustotal.com/en/file/511adc6c5f1fdf45cc0e266b7ab052c64f4620fed3c982e23d8e3c2f49c8a818/analysis/

But when in doubt, double check your hashes!

**Comment by kurisubrooks** [comment]
Thanks a bunch! @ixe013

**Comment by bew-dev** [comment]
i came across this issue link, when searching for potential malware.  i came home today, out of the blue i get this popup, two of them identical actually, they say the following;

`Notifu uses IUserNotification to display a yellow pop-up baloon.....
...paralint.com/notifu/.BSD Licensed.`

Then looking in the task tray, and systray (win7 box) i see the the yellow icon.  i do not have node installed, but i an running laravel through putty for devloping of that site via network share.

Opening process manager, i see two instances, and file location is here 
`D:\dusers\<myusername>\AppData\Local\Temp\nw4612_13980\node_modules\node-notifier\vendor\notifu` and there is anotifu64.exe in there also.  

again i do not have node installed, and my system has been clean.  I DO have Gitter installed, and DO below to the node group, have i maybe been implanted through Gitter some how?  

Any ideas?  Im about to embark on a rootkit scan, or something...

**Comment by MadLittleMods** [comment]
@bew-dev The [Gitter desktop client uses `node-notifier@4.5.0`](https://gitlab.com/gitlab-org/gitter/desktop/blob/713189dba636eda37d5c38f3dd6a7f4536beca48/nwapp/package.json#L36) which will spawn a separate process when popping a notification.

Which version of Windows are you using? I haven't come across that error before but I normally use the webapp on a daily basis. 

In the future, we plan to use the native [`Notification`](https://github.com/nwjs/nw.js/wiki/Notification) API in NW.js.

**Comment by brian-lamb-software-engineer** [comment]
Win7Ultx64.  First time I have seen it as well.  Thanks for the info.

**Comment by ixe013** [comment]
Hi @bew-dev , node notification bundles my [minuscule notification display tool](https://www.paralint.com/projects/notifu/). A recent change in Windows 10 added some text to every notification displayed. 

I just [created a pull request](https://github.com/mikaelbr/node-notifier/pull/186) to have the updated binaries included in the main package. You'll find more details about the change over there.

In the meantime, you can replace the `notifu.exe` and `notifu64.exe` under vendor/notifu for that packages with the ones from my fork, available here : [https://github.com/ixe013/node-notifier/tree/master/vendor/notifu](https://github.com/ixe013/node-notifier/tree/master/vendor/notifu).
