### ISSUE TITLE
.on('click') fires multiple times on subsequent notifications.

### ISSUE THREAD

**Issue by mmoreno509** [mikaelbr/node-notifier#89]
I have a program that fires a notification when it receives a message through ipc:

    ipcMain.on('message.received', function(event, message) {
		var room = {
			type : message.room.type,
			id : ((message.room.type == 'room') ? message.domain_user_id : message.room.id)
		}

		console.log('message.received.event', message.body.msg, room);
		
		if(!win.isFocused()){
			Notifier.notify({
				title 		: message.body.sender + ' says:',
				message 	: message.body.msg[0].content,
				wait 		: true
			}).on('click', function(){
				console.log('notifier clicked');
				win.show();
				win.focus();
				win.webContents.send('open.message', room );
			});

			App.dock.bounce('informational');
		}
	});

The event is fired correctly and everything seems to work fine, except after the second message, the click event is fired 2, the third message fires it 3 times....

Here is the output:

    message.received.event [ { content: 'test message 1', type: 'text' } ] { type: 'room', id: 6 }
    notifier clicked
    message.received.event [ { content: 'test message 2', type: 'text' } ] { type: 'room', id: 6 }
    notifier clicked
    notifier clicked
    message.received.event [ { content: 'test message 3', type: 'text' } ] { type: 'room', id: 6 }
    notifier clicked
    notifier clicked
    notifier clicked

Not entirely sure why it rebinds the click callback with every subsequent notifiication

**Comment by alexandrkazah** [comment]
I have a same problem. Did you find the solution?

**Comment by black-snow** [comment]
Should be the `#1` thing to fix IMHO. Rendering the notifier useless for me :(

**Comment by black-snow** [comment]
@mikaelbr Are there any updates on this one?

**Comment by mikaelbr** [comment]
Hi! I've been looking into this some, and I'm leaning towards this maybe being a misuse case. `notifier` in this case is a eventlistener object, and `notify` is a chainable function/method call. So by doing this:

```
notifier.notify('message 1').on('click', ...);
notifier.notify('message 2').on('click', ...);
```

Is the same as doing this:

```
notifier.on('click', ...);
notifier.on('click', ...);

notifier.notify('message 1');
notifier.notify('message 2');
```

This is by design as the `on click` event is ment to be a global event listener to capture all interaction. The callback is ment to be specific per notification. This can be tested by doing this:

```js
notifier.notify({
    title: 'Notification 1',
    message: 'Notification 1',
    sound: true,
    wait: true
}, function () { console.log('interact 1'); });

setTimeout(function () {
  notifier.notify({
    title: 'Notification 2',
    message: 'Notification 2',
    sound: true,
    wait: true
  }, function () { console.log('interact 2'); });
}, 1500);
```

If you click on the notification before the 1500ms, `interact 1` will display, and again `interact 2` if you click the second notifications which appears after 1500ms. However with Mac Notification Center (unsure at the moment on Windows and Linux as I don't have that available right now), if there is no timeout both notifications are grouped as the same notification and both callbacks will be triggered on click. This isn't necessarily wrong, as the notifications are kind of one - but it can be unexpected.

---

@mmoreno509 I think the issue you are having here is that you add a new listener on every `message.received`. Try doing something like this instead:

```js
var room;
notifier.on('click', function(){
  console.log('notifier clicked');
  win.show();
  win.focus();
  win.webContents.send('open.message', room );
});

ipcMain.on('message.received', function(event, message) {
  room = {
    type : message.room.type,
    id : ((message.room.type == 'room') ? message.domain_user_id : message.room.id)
  };
  if(!win.isFocused()){
    notifier.notify({
      title       : message.body.sender + ' says:',
      message     : message.body.msg[0].content,
      wait        : true
    });
    App.dock.bounce('informational');
  }
});
```

But that might seem hacky, so try using the one-off callback instead of adding a new listener for each message:

```js
ipcMain.on('message.received', function(event, message) {
  var room = {
    type : message.room.type,
    id : ((message.room.type == 'room') ? message.domain_user_id : message.room.id)
  };
  if(!win.isFocused()){
    notifier.notify({
      title       : message.body.sender + ' says:',
      message     : message.body.msg[0].content,
      wait        : true
    }, function (error, result) {
      if (result !== 'activate') {
        // not clicked, so don't do anything
        return;
      }
      console.log('notifier clicked');
      win.show();
      win.focus();
      win.webContents.send('open.message', room );
    });
    App.dock.bounce('informational');
  }
});
```

---

@black-snow Much of the same goes for you. Try either just using a single listener or one of the one-off callbacks. You can also use the fact that `node-notifier` allows you to pass custom transitive options to your listeners like so:

```js
import notifier from 'node-notifier'

// Just add one time
notifier.on('click', function (obj, options) {
  if (options.myCustomAction) {
    options.myCustomAction(); // invoke the custom action passed.
  }
});

// on some event do
notifier.notify({
  title: ...,
  message: ...,
  sound: true,
  wait: true,
  // Pass action as function
  myCustomAction: openFileExplorer
})

// on incoming connections do
notifier.notify({
  title: ...,
  message: ...,
  sound: true,
  wait: true,
  // Pass action as function
  myCustomAction: openSomeDialogThatWillCauseSomeEventOnConfirm
});
```

---

Hope this helps you both!

**Comment by black-snow** [comment]
@mikaelbr Hey, thanks for the fast and thorough reply.
The API felt somewhat quirky (*for my usecase*) and I was wondering if I had to use a single function to handle all click events. But that seemed wrong to me. Will give it a shot tomorrow!

Maybe we should clarify the click-handling in the docs. Will think about that tomorrow, too.
Thanks again! Will report back soon.

**Comment by black-snow** [comment]
Works great. I now have a single handler function that executes the callbacks I pass to it via options.

**Comment by mikaelbr** [comment]
Great! Does this mean this can be closed?

**Comment by black-snow** [comment]
@mikaelbr I'd say so.

**Comment by mikaelbr** [comment]
Brilliant. Thanks for posting an issue! 👍

**Comment by fzs1994** [comment]
@mikaelbr I'm still facing issue. I tried the above solution but not working. "electron": "^10.1.5", "node-notifier": "5.4.3",

**Comment by fzs1994** [comment]
Here is my code. I already tried with above solution, but not working.
```
ipcMain.on('sendNotification', (event, payload: any) => {
    notifier.notify(
      {
        appID: 'ZinniaX-ChatHub',
        title: payload.notification.title,
        message: payload.notification.body,
        icon: path.join(__dirname, '/../../src/assets/icon.ico'),
        sound: false,
        wait: true
      },
      (err, response) => {
        if (err) {
          return;
        }
      }
    );

    notifier.on('click', function (notifierObject, options, event) {
      win.show();
      win.webContents.send('notification-clicked');
    });
  });
```

**Comment by fzs1994** [comment]
@mikaelbr Click event doesn't work on v9.0.0

**Comment by fzs1994** [comment]
I resolved it by using `notifier.removeAllListeners();`
Also there was another issue with `ipcRenderer.on` so I used `ipcRenderer.once` and it resolved my issue. Thanks!
