### ISSUE TITLE
Icons are not showing in Wndows 7

### ISSUE THREAD

**Issue by sunojvijayan** [mikaelbr/node-notifier#90]
Tried to create a notification for windows 7 shows balloon but not image and toast. Please help.

**Comment by kurisubrooks** [comment]
Hi, can I please see the code you're using to trigger the notification?

**Comment by sunojvijayan** [comment]
notifier.notify({
            title: 'It4u Notification',
            message: 'Your Ticket has been escalated',
            icon: path.join(__dirname, 'assets/img/bg_login33.jpg'), // absolute path (not balloons) 
            sound: true, // Only Notification Center or Windows Toasters 
            wait: true // wait with callback until user action is taken on notification 
        }, function (err, response) {
            // response is response from notification 
        });

**Comment by kurisubrooks** [comment]
Windows Notification icons can only be .png or .ico files.

**Comment by sunojvijayan** [comment]
I tried png files also but not showing

**Comment by kurisubrooks** [comment]
Try `path.join(__dirname, './assets/img/{icon}')` as your image path. 
Replace `{icon}` with the icon file name.

Are you 32 or 64 bit?

**Comment by sunojvijayan** [comment]
64
