### ISSUE TITLE
Use image url for notifier icon parameter

### ISSUE THREAD

**Issue by kingdido999** [mikaelbr/node-notifier#93]
This is just a feature request. For the notify method, I want to display an icon from url. I know I could download the image from url, pass its path to `icon` parameter and then delete the file... I'm wondering if it would be possible to pass in an url as icon parameter?

**Comment by kurisubrooks** [comment]
I'm worried that this will just add some more problems to node-notifier, and make the notification longer to load. The way we'd accomplish this is by checking if the icon is a url, then we'd download it to a temp folder, then make it use this temporary icon, deliver the notification, delete it after so it doesn't waste space on disk.

Add time to the loading of the notification, send a network request, deal with automated file permissions...
I don't think this is a very good idea. It's easier just to download a single icon, and include it in code.

**Comment by mikaelbr** [comment]
Good points, @kurisubrooks! I don't feel this should be the responsibility of node-notifier. If this feature is really wanted, I feel it would be better to extend node-notifier, wrapping it in a function that fetches the icon url. Extending, but not changing.

**Comment by sant123** [comment]
@kurisubrooks @mikaelbr I know this is not Chromium, but here we will find an API that easily adds notifications with relative, absolute and url path to an image, I say this because if we use Electron for making notifications and then use the API, we will get our image in any of the path types above.

**Comment by kurisubrooks** [comment]
@sant123 In what way would something like this be used? What use application? I still don't see this as a good idea.

**Comment by averissimo** [comment]
For instance, when user's avatars are stored online: hangouts and gravatar are some examples.
