### ISSUE TITLE
Where is the source of the vendor code?

### ISSUE THREAD

**Issue by MadLittleMods** [mikaelbr/node-notifier#96]
Is the source for the code `./vendor` available?

I am specifically curious about the [toaster](https://github.com/mikaelbr/node-notifier/tree/master/vendor/toaster) for Windows and how you are managing whether to play the sound or not.

**Comment by MadLittleMods** [comment]
Found it here: https://github.com/nels-o/toaster [linked in the readme](https://github.com/mikaelbr/node-notifier#usage-windowstoaster)

**Comment by kurisubrooks** [comment]
Our fork of the source is here:
https://github.com/mikaelbr/toaster

**Comment by kurisubrooks** [comment]
Looks like it hasn't been updated, nor, has any progress in it. So @nels-o 's is probably the most up-to-date!

**Comment by MadLittleMods** [comment]
Thanks @kurisubrooks I don't see anything about the `sound` parameter in the toast.exe source code in either but I can confirm it works in `node-notifier`

**Comment by MadLittleMods** [comment]
Looking at the mikaelbr/toaster#silent` branch `./toast/Program.cs` has `-q` parameter to disable sound.
