### ISSUE TITLE
Windows 8.1 does not support `file:///xxx` protocol icon paths

### ISSUE THREAD

**Issue by MadLittleMods** [mikaelbr/node-notifier#99]
When using a `file:///xxx` protocol path for the icon, it will just fail on Windows 8.1. I do see that documentation always says to use absolute paths and doesn't mention file protocol paths; It was an oversight on my part because I was refactoring an [nw.js app using `window.Notifcation` where `file:///` is needed](https://github.com/nwjs/nw.js/wiki/Notification#toast-notification-requires-node-webkit--v011).

Platform test results when using `file:///xxx` paths (`node-notifier@4.5.0`):

 - OSX: Works
 - Windows 10: Works
 - Windows 8.1: Does not work

Example:

```js
var notifier = require('node-notifier');

notifier.notify({
  'title': 'Heya',
  'message': 'foo bar',
  'icon': 'file:///C:/some-project/mlm.png'
  //'icon': 'file:///C:\\some-project\\mlm.png'
});
```

![](http://i.imgur.com/9YHTzEk.png)

**Comment by kurisubrooks** [comment]
From my knowledge, you're only able to provide the file's absolute path, by means of `path`, `__dirname`, and specified other methods. Opening via the `file://` protocol is not supported.

**Comment by mikaelbr** [comment]
We could possibly patch the paths on Windows 8.1 to remove the scheme, to make it work.

**Comment by MadLittleMods** [comment]
@mikaelbr :+1: That is also what I had in mind
